<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>DISPLACE West Coast documentation - 1&nbsp; Populations data</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./fisheries.html" rel="next">
<link href="./index.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

<script src="site_libs/kePrint-0.0.1/kePrint.js"></script>
<link href="site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./populations.html"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Populations data</span></a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">DISPLACE West Coast documentation</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduction</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./populations.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Populations data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./fisheries.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Fisheries data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./results.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Results</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#sec-parametrization-populations" id="toc-sec-parametrization-populations" class="nav-link active" data-scroll-target="#sec-parametrization-populations"><span class="header-section-number">1.1</span> Populations</a></li>
  <li><a href="#stock-biological-traits" id="toc-stock-biological-traits" class="nav-link" data-scroll-target="#stock-biological-traits"><span class="header-section-number">1.2</span> Stock biological traits</a>
  <ul class="collapse">
  <li><a href="#sablefish" id="toc-sablefish" class="nav-link" data-scroll-target="#sablefish"><span class="header-section-number">1.2.1</span> Sablefish</a></li>
  <li><a href="#dover-sole" id="toc-dover-sole" class="nav-link" data-scroll-target="#dover-sole"><span class="header-section-number">1.2.2</span> Dover Sole</a></li>
  <li><a href="#longspine-thornyhead" id="toc-longspine-thornyhead" class="nav-link" data-scroll-target="#longspine-thornyhead"><span class="header-section-number">1.2.3</span> Longspine Thornyhead</a></li>
  <li><a href="#shortpine-thornyhead" id="toc-shortpine-thornyhead" class="nav-link" data-scroll-target="#shortpine-thornyhead"><span class="header-section-number">1.2.4</span> Shortpine Thornyhead</a></li>
  <li><a href="#sizespectra-option-parameters" id="toc-sizespectra-option-parameters" class="nav-link" data-scroll-target="#sizespectra-option-parameters"><span class="header-section-number">1.2.5</span> SizeSpectra option parameters</a></li>
  </ul></li>
  <li><a href="#species-distribution" id="toc-species-distribution" class="nav-link" data-scroll-target="#species-distribution"><span class="header-section-number">1.3</span> Species distribution</a></li>
  <li><a href="#abundances-szgroup" id="toc-abundances-szgroup" class="nav-link" data-scroll-target="#abundances-szgroup"><span class="header-section-number">1.4</span> Stock abundances at szgroup</a>
  <ul class="collapse">
  <li><a href="#stock-abundances-at-age" id="toc-stock-abundances-at-age" class="nav-link" data-scroll-target="#stock-abundances-at-age"><span class="header-section-number">1.4.1</span> Stock abundances at age</a></li>
  </ul></li>
  <li><a href="#stock-prices-data" id="toc-stock-prices-data" class="nav-link" data-scroll-target="#stock-prices-data"><span class="header-section-number">1.5</span> Stock prices data</a></li>
  <li><a href="#files-overlook" id="toc-files-overlook" class="nav-link" data-scroll-target="#files-overlook"><span class="header-section-number">1.6</span> Files overlook</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span id="sec-populations" class="quarto-section-identifier"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Populations data</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<!-- (ref:lovelace) @Lovelace1842 -->
<section id="sec-parametrization-populations" class="level2" data-number="1.1">
<h2 data-number="1.1" class="anchored" data-anchor-id="sec-parametrization-populations"><span class="header-section-number">1.1</span> Populations</h2>
<p>This section includes a description of the raw input datasets and the parameters considered to run the R routines for the target species population characteristics. These files should be stored and loaded from <code>DISPLACE_raw_inputs/{project-name}/POPULATIONS</code>.</p>
<p>Commercial species included in this study:</p>
<ul>
<li>Sablefish (<em>Anoplopoma fimbria</em>) (FAO code <strong>SAB</strong>): Status along the U.S. West Coast in 2023.</li>
<li>Dover Sole (<em>Microstomus pacificus</em>) (FAO code <strong>MIP</strong>): Stock assessment along the U.S. West Coast in 2021.</li>
<li>Longspine Thornyhead (<em>Sebastolobus altivelis</em>) (FAO code <strong>SJZ</strong>): Biological data from stock assessments in California, Oregon, and Washington in 2013.</li>
<li>Shortspine Thornyhead (<em>Sebastolobus alascanus</em>) (FAO code <strong>SJU</strong>): Status along the U.S. West Coast in 2023.</li>
</ul>
<p>We are focusing on these species because, aside from albacore—which we can’t model due to the fishery’s range—they are the most common in the lease areas. While swordfish is also common, its fishery is about to close, so we did not include it. These species also represent the highest landings by weight and value (though sablefish prices have recently dropped). Although crab and squid have the highest overall landings, they are primarily caught nearshore and are therefore not impacted by the leases. The fisheries of this species is also known ans DTS (Deepwater Trawl complex Species).</p>
</section>
<section id="stock-biological-traits" class="level2" data-number="1.2">
<h2 data-number="1.2" class="anchored" data-anchor-id="stock-biological-traits"><span class="header-section-number">1.2</span> Stock biological traits</h2>
<p>This section describes the contents of the file <code>Stock_biological_traits.csv</code>. Most of the data is extracted from the stock assessments approved by the Pacific Fishery Management Council during the <a href="https://www.pcouncil.org/briefing-book/september-2023-briefing-book/#g.-groundfish-management-toc-7c35d77a-c671-4a15-b867-e7c17b4b2deb">September 2023 Council Meeting</a>.</p>
<p>Besides specific parameter values for each species, detailed in the subsequent sections, the following variables are also included in <code>Stock_biological_traits.csv</code>:</p>
<ul>
<li><code>UseIt</code>: values Yes/No, indicating whether it is included in the analysis or not.</li>
<li><code>stock</code>: code of the population. For our study case this corresponds to the FAO code.</li>
<li><code>species</code>: Species scientific name.</li>
<li><code>Source_Biology</code> and <code>Source_Stock</code>: references from where the values are taken.</li>
</ul>
<p><code>Stock_biological_traits.csv</code> also contains details on the input size bins in DISPLACE, as defined in <code>Stock_abundances_at_szgroup.csv</code>.Using the maximum length values across all DTS species, we set a <code>sz_bin_cm</code> of 6 (in cm) based on the <code>unit_sizebin</code>, where a value of <code>1</code> is used. For more details, refer to the section on <a href="#abundances-szgroup">abundance by size</a>.</p>
<section id="sablefish" class="level3" data-number="1.2.1">
<h3 data-number="1.2.1" class="anchored" data-anchor-id="sablefish"><span class="header-section-number">1.2.1</span> Sablefish</h3>
<p>(<em>Anoplopoma fimbria</em>) (FAO code SAB)</p>
<hr>
<p><em>Note: For cases with sexual dimorphism, the average value across both females and males is used.</em></p>
<section id="somatic-growth" class="level4" data-number="1.2.1.1">
<h4 data-number="1.2.1.1" class="anchored" data-anchor-id="somatic-growth"><span class="header-section-number">1.2.1.1</span> Somatic growth</h4>
<ul>
<li><p><code>Linf</code>: Asymptotic length. Sablefish stock assessments assumes Schnute growth rather than von Bertalanffy growth. Since DISPLACE does not incorporate Schnute, we will derive Bertalanffy parameters from those in Schnute.</p>
<p>The von Bertalanffy growth function is given by the folowwing expression:</p></li>
</ul>
<p><span class="math display">\[
L(t)=L_∞(1−e^{−K(t−t_0)})
\]</span></p>
<pre><code>The four-parameter growth function from Schnute can be defined as:</code></pre>
<p><span class="math display">\[
L(t) =  L_1 + \left( L_2 - L_1 \right) \frac{1 - e^{-K(t - t_1)}}{1 - e^{-K(t_2 - t_1)}}
\]</span></p>
<div class="cell" data-hash="populations_cache/html/tbl-sablefish-Schnute_10c16d55f192c29751a2c4f8c876dc16">
<div class="cell-output-display">
<div id="tbl-sablefish-Schnute" class="anchored">
<table class="table table-sm table-striped small">
<caption>Table&nbsp;1.1: Schnute and von Bertalanffy growth parameters for Sablefish.</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Parameter</th>
<th style="text-align: right;">Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Length-at-age min (female)</td>
<td style="text-align: right;">25.262</td>
</tr>
<tr class="even">
<td style="text-align: left;">Length-at-age max (female)</td>
<td style="text-align: right;">61.130</td>
</tr>
<tr class="odd">
<td style="text-align: left;">von Bertalanffy K (female)</td>
<td style="text-align: right;">0.367</td>
</tr>
<tr class="even">
<td style="text-align: left;">Length-at-age min (male)</td>
<td style="text-align: right;">26.621</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Length-at-age max (male)</td>
<td style="text-align: right;">56.111</td>
</tr>
<tr class="even">
<td style="text-align: left;">von Bertalanffy K (male)</td>
<td style="text-align: right;">0.381</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>We can get <span class="math inline">\(L_2\)</span> from <code>Length-at-age max (female)</code> is 61.130 and <code>(male)</code> 56.111, and <span class="math inline">\(L_1\)</span> from <code>Length-at-age max (female)</code> is 25.262 and <code>(male)</code> 26.621 in page 27, table 2 (<span class="citation" data-cites="johnson2023sablefish">Johnson, Wetzel, and Tolimieri (<a href="references.html#ref-johnson2023sablefish" role="doc-biblioref">2023</a>)</span>). Further, <span class="math inline">\(K\)</span> corresponds to 0.367 <span class="math inline">\(yr^{-1}\)</span> for females and 0.381 <span class="math inline">\(yr^{-1}\)</span> for males from page 10 and from <code>von Bertalanffy K</code> variables in page 27, table 2 (<span class="citation" data-cites="johnson2023sablefish">Johnson, Wetzel, and Tolimieri (<a href="references.html#ref-johnson2023sablefish" role="doc-biblioref">2023</a>)</span>) (<a href="#tbl-sablefish-Schnute">Table&nbsp;<span>1.1</span></a>). Regarding <span class="math inline">\(t_1\)</span> and <span class="math inline">\(t_2\)</span>, these can be found on the benchmark assessment <span class="citation" data-cites="haltuch2019sablefish_benchmark">M. A. Haltuch et al. (<a href="references.html#ref-haltuch2019sablefish_benchmark" role="doc-biblioref">2019</a>)</span>, section 3.3, page 54, on general model specifications, corresponding to 0.5 and 30 years respectively.</p>
<p>If we derive <code>LInf</code> from Schnute we get:</p>
<p><span class="math display">\[
L_{\infty} = \frac{L_2 - L_1 \cdot e^{-K(t_2 - t_1)}}{1 - e^{-K(t_2 - t_1)}}
\]</span></p>
<p>Based on the parameters available in the assessment, we will calculate <code>Linf</code> independently for males and females. The average value across both will be inputted into DISPLACE and corresponds to 58.6210501.</p>
<p>Alternatively, if the values from the stock assessment could not be derived, we could have considered using the value of 63.67 cm from Table 6 in <span class="citation" data-cites="head2014sablefish">M. A. Head, Keller, and Bradburn (<a href="references.html#ref-head2014sablefish" role="doc-biblioref">2014</a>)</span> publication. However, we are including these here merely as a reference.</p>
<ul>
<li><p><code>CV_Linf</code>: We only have Schnute parameters available. In this case, we will use the average of the <code>Growth CV old</code> values, as they are the closest to <code>Linf</code> and can serve as a proxy. These correspond to <code>Growth CV old (female)</code> (0.103) and <code>(male)</code> (0.078) in page 27, table 2 (<span class="citation" data-cites="johnson2023sablefish">Johnson, Wetzel, and Tolimieri (<a href="references.html#ref-johnson2023sablefish" role="doc-biblioref">2023</a>)</span>). Mean value used 0.0905.</p></li>
<li><p><code>K</code>: Von Bertalanffy <span class="math inline">\(K\)</span>. 0.367 <span class="math inline">\(yr^{-1}\)</span> for females and 0.381 <span class="math inline">\(yr^{-1}\)</span> for males from page 10 and from <code>von Bertalanffy K</code> variables in page 27, table 2 (<span class="citation" data-cites="johnson2023sablefish">Johnson, Wetzel, and Tolimieri (<a href="references.html#ref-johnson2023sablefish" role="doc-biblioref">2023</a>)</span>). Mean value used 0.374 <span class="math inline">\(yr^{-1}\)</span>.</p></li>
<li><p><code>t0</code>: Theoretical age of the von Bertalanffy growth function (VBGF) at which fish would have a size of zero. Again, we need to consider that the stock assessment express growth using Schnute parameters. Thus we’ll need to derive <span class="math inline">\(t_0\)</span> from:</p></li>
</ul>
<p><span class="math display">\[
t_0 = t_1 + \frac{1}{K} \ln \left( \frac{L_2 - L_1}{L_2 - L_1 \cdot e^{-K(t_2 - t_1)}} \right)
\]</span></p>
<p>This yields a <code>t0</code> of -1.1883843, which we will use. For reference, Table 7 from <span class="citation" data-cites="head2014sablefish">M. A. Head, Keller, and Bradburn (<a href="references.html#ref-head2014sablefish" role="doc-biblioref">2014</a>)</span> provides an overall estimate of -1.28 years. <span style="color:orange; font-weight:bold;">TO DISCUSS</span></p>
<ul>
<li><code>CV_recru</code>: Coefficient of variation in recruitment. Table 2, on page 27 from the stock assessment, includes all model parameters. Among others, it defines recruitment variability (<span class="math inline">\(\sigma R\)</span>), which corresponds to the standard deviation of the log-scale recruitment deviations (<span class="citation" data-cites="johnson2023sablefish">Johnson, Wetzel, and Tolimieri (<a href="references.html#ref-johnson2023sablefish" role="doc-biblioref">2023</a>)</span>). Then the coefficient of variation (CV) of recruitment can be estimated from this parameter as follows:</li>
</ul>
<p><span class="math display">\[
CV = \sqrt{ \exp(\sigma R^2) - 1 }
\]</span></p>
<p>Thus, for <span class="math inline">\(\sigma R = 1.4\)</span>, the CV will be 2.4696816.</p>
</section>
<section id="length-weight-relationship" class="level4" data-number="1.2.1.2">
<h4 data-number="1.2.1.2" class="anchored" data-anchor-id="length-weight-relationship"><span class="header-section-number">1.2.1.2</span> Length-weight relationship</h4>
<p>Length-weight relationship expression: <span class="math inline">\(W = aL^b\)</span></p>
<ul>
<li><p><code>a</code>: Weight-length coefficient. Female 3.315e-06 and male 3.371e-06 from table 11 (<span class="citation" data-cites="haltuch2019sablefish">M. Haltuch et al. (<a href="references.html#ref-haltuch2019sablefish" role="doc-biblioref">2019</a>)</span>). Mean value used 3.343^{-6}.</p></li>
<li><p><code>b</code>: Weight-length exponent. Female 3.27264 and male 3.27008 from table 11 (<span class="citation" data-cites="haltuch2019sablefish">M. Haltuch et al. (<a href="references.html#ref-haltuch2019sablefish" role="doc-biblioref">2019</a>)</span>). Mean value used 3.27136.</p></li>
</ul>
</section>
<section id="maturity" class="level4" data-number="1.2.1.3">
<h4 data-number="1.2.1.3" class="anchored" data-anchor-id="maturity"><span class="header-section-number">1.2.1.3</span> Maturity</h4>
<ul>
<li><p><code>L50</code>: Length 50% mature. Overall value of 54.64 cm (used in Marlin) from all geographic areas and depths combined from Table 3 (<span class="citation" data-cites="head2014sablefish">M. A. Head, Keller, and Bradburn (<a href="references.html#ref-head2014sablefish" role="doc-biblioref">2014</a>)</span>). Alternative value of 55.190 from table 11 (<span class="citation" data-cites="haltuch2019sablefish">M. Haltuch et al. (<a href="references.html#ref-haltuch2019sablefish" role="doc-biblioref">2019</a>)</span>). Both values correspond to female lengths. We will use the average from both assessments.</p>
<p>To determine the male’s <code>L50</code>, we can use the proportion of <code>L50</code> to <code>Linf</code> observed in females. Given that the female <code>Linf</code> is 61.130 cm and the female <code>L50</code> is 54.915 cm (from the average of the available values), we first calculate the proportion of <code>L50</code>to <code>Linf</code> for females (0.8983314). We then apply this same proportion to the male <code>Linf</code> (56.111 cm) to find the male <code>L50</code> (50.4062746cm). We will use the mean value between female and the calcualted male lengths 52.6606373 cm. (This value is also given to the DISPLACE parameter <code>mat</code>).</p></li>
<li><p><code>mat_cat</code>: This corresponds to the maturity size DISPLACE category at the L50. Given <code>0:13</code> bins and a <code>sz_bin_cm</code> of 6, as defined earlier, the corresponding bin index for an <code>L50</code> of 52.6606373 cm is 9.</p>
<p><strong>NOTE: Bastardie described it with the following example: if there are 5 cm bins (<code>0, 1, 2, 3, 4, 5</code>) and the L50 maturity size is 14 cm, then the <code>mat_cat</code> should be <code>3</code>. However, this raises the question: does <code>mat_cat = 3</code> correspond to the third bin (index <code>2</code> in zero-based indexing)? Or should it instead be recoded to <code>2</code> to consider initial value of zero?</strong></p></li>
<li><p><code>r_age</code>: Age of recruitment. (Not used in DISPLACE, but included in the input files as a reference). As a reference here we will use <code>A50</code>, having a value of 6.86 from table 5 (<span class="citation" data-cites="head2014sablefish">M. A. Head, Keller, and Bradburn (<a href="references.html#ref-head2014sablefish" role="doc-biblioref">2014</a>)</span>) and a value of 5 from <span class="citation" data-cites="guzman2017sablefish">Guzmán et al. (<a href="references.html#ref-guzman2017sablefish" role="doc-biblioref">2017</a>)</span>, yielding an average value of 5.93, corresponding to the one used in Marlin. We should note that <span class="citation" data-cites="guzman2017sablefish">Guzmán et al. (<a href="references.html#ref-guzman2017sablefish" role="doc-biblioref">2017</a>)</span> value is not based on their own data but on two outdated paper estimates (Fujiwara and Hankin (1988) and Parks and Shaw (1987)). Alternatively we could also use <span class="citation" data-cites="rodgveller2016sablefish">Rodgveller, Stark, and Echave (<a href="references.html#ref-rodgveller2016sablefish" role="doc-biblioref">2016</a>)</span> values from table 2, although these are specific from Alaska populations. Since DISPLACE does not require this parameter, we will exclusively reference that from <span class="citation" data-cites="head2014sablefish">M. A. Head, Keller, and Bradburn (<a href="references.html#ref-head2014sablefish" role="doc-biblioref">2014</a>)</span>.</p>
<p><strong>Note: Despite not being used for DISPLACE parametrization, the parameter is read and it is used within <code>GeneratePopulationsFeatures.R</code>. High values trigger <code>Error in As[r_age + 1, ] : subscript out of bounds</code> associated to line 552 of the R routine. Thus we will specify <code>NA</code> and no <code>A50</code> value as a reference. Need to confirm with Bastardie whether this is actually affecting the parametrization.</strong></p></li>
<li><p><code>ssb_assessment</code>: Total weight of the sexually mature (i.e., capable of reproduction) part of a fish population. Spawning Stock Biomass in mT from page 38, table 4 (<span class="citation" data-cites="johnson2023sablefish">Johnson, Wetzel, and Tolimieri (<a href="references.html#ref-johnson2023sablefish" role="doc-biblioref">2023</a>)</span>). DISPLACE does not allow to include different SSB by year simulated. Instead we can choose values from one year or an average value across simulated years. For our analysis we will use that from the year 2010, when our simulation starts (86995 mT). (Not used in DISPLACE, but included in the input files as a reference)</p></li>
</ul>
</section>
<section id="sec-recruitmet-intro" class="level4" data-number="1.2.1.4">
<h4 data-number="1.2.1.4" class="anchored" data-anchor-id="sec-recruitmet-intro"><span class="header-section-number">1.2.1.4</span> Recruitment</h4>
<section id="alpha-beta" class="level5" data-number="1.2.1.4.1">
<h5 data-number="1.2.1.4.1" class="anchored" data-anchor-id="alpha-beta"><span class="header-section-number">1.2.1.4.1</span> alpha &amp; beta</h5>
<ul>
<li><code>alpha</code> and <code>beta</code>: Parameters from the Ricker recruitment model. The available stock assessments for DTS use the Beverton-Holt stock-recruitment relationship. While Beverton-Holt can be expressed in terms of alpha and beta, our stock assessments use the steepness formulation. Thus, we need to transform our expressions to:</li>
</ul>
<p><span class="math display">\[
R = \frac{\alpha S}{1 + \beta S}
\]</span></p>
<p>The parameters are given by:</p>
<p><span class="math display">\[
\beta = \frac{5h-1}{4hR_0} \quad \text{and} \quad \alpha = SPR_0 \left(\frac{1-h}{4h}\right)
\]</span></p>
<p>Thus we can calculate <code>alpha</code> and <code>beta</code> from <span class="math inline">\(h\)</span> (steepness), <span class="math inline">\(R_0\)</span> (recruitment at unfished equilibrium), and <span class="math inline">\(SPR_0\)</span> (spawning potential ratio at unfished equilibrium).</p>
<ul>
<li><span class="math inline">\(h\)</span>: steepness is 0.7, as described in the model parameters section 3.2.7, page 9 (<span class="citation" data-cites="johnson2023sablefish">Johnson, Wetzel, and Tolimieri (<a href="references.html#ref-johnson2023sablefish" role="doc-biblioref">2023</a>)</span>).</li>
<li><span class="math inline">\(R_0\)</span>: value 19453.9 from at table 10 (<span class="citation" data-cites="johnson2023sablefish">Johnson, Wetzel, and Tolimieri (<a href="references.html#ref-johnson2023sablefish" role="doc-biblioref">2023</a>)</span>).</li>
<li><span class="math inline">\(SPR_0\)</span>: In Table 10 we can find several SPR values, but none for the unfished equilibrium (<span class="citation" data-cites="johnson2023sablefish">Johnson, Wetzel, and Tolimieri (<a href="references.html#ref-johnson2023sablefish" role="doc-biblioref">2023</a>)</span>). <span style="color:red; font-weight:bold;">MISSING</span></li>
</ul>
</section>
<section id="fixed-recruitment" class="level5" data-number="1.2.1.4.2">
<h5 data-number="1.2.1.4.2" class="anchored" data-anchor-id="fixed-recruitment"><span class="header-section-number">1.2.1.4.2</span> Fixed recruitment</h5>
<ul>
<li><p><code>fixed recruitment</code>:</p>
<p>In the meantime, while we are unable to define the Beverton-Holt relationship using alpha and beta, we will set a fixed recruitment. The model type can be specified in files like <code>0spe_SSB_R_parameters_biolsce1.dat</code>, where the first value represents <code>alpha</code>, followed by <code>beta</code> and <code>CV_recru</code>. The last value determines the recruitment model to use: <code>0</code> for Ricker, <code>1</code> for Beverton-Holt, and <code>2</code> for fixed recruitment. To apply fixed recruitment (code <code>2</code>), <code>alpha</code> should specify the number of recruits in thousands, while <code>beta</code> is set to 0.</p>
<p>For example, in the input file for population <code>0</code> (e.g., <code>0spe_SSB_R_parameters_biolsce1.dat</code>), the configuration could consist of three rows (excluding <code>CV_recru</code>), with values: 72585, 0 and 2. This setup instructs DISPLACE to assign a fixed recruitment of <code>72585*1000</code> individuals at the start of each year (<span class="math inline">\(y\)</span>) for population <code>0</code>.</p>
<p>Despite Sablefish recruitment being estimated to have been quite variable, with large amounts of uncertainty in individual recruitment events as seen in Table iii from <span class="citation" data-cites="johnson2023sablefish">Johnson, Wetzel, and Tolimieri (<a href="references.html#ref-johnson2023sablefish" role="doc-biblioref">2023</a>)</span> (<a href="#tbl-sablefish-recruitment">Table&nbsp;<span>1.2</span></a>), we will use, as a first approximation, the mean value from the time series recruitment (5.0930741^{4} in thousands), while we await to define BH parameters to define recruitment within the model.</p>
<p>The DISPLACE R routines are set to write the <code>{pop_code}spe_SSB_R_parameters_biolsce{q}.dat</code> file using either the Ricker or Beverton-Holt (BH) structures. We will generate the file contents for each population and store them in the <code>DISPLACE_raw_inputs/{project-name}/POPULATIONS</code> directory. From these, the respective files will be updated when running <code>GeneratePopulationsFeatures.R</code> (update in line 748).</p></li>
</ul>
<div class="cell" data-hash="populations_cache/html/tbl-sablefish-recruitment_861c4289f92aee558e4182f2d36fbf22">
<div class="cell-output-display">
<div id="tbl-sablefish-recruitment" class="anchored">
<table class="table table-sm table-striped small">
<caption>Table&nbsp;1.2: Estimated recent trend in recruitment (1,000s) for Sablefish.</caption>
<colgroup>
<col style="width: 17%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 7%">
<col style="width: 7%">
</colgroup>
<tbody>
<tr class="odd">
<td style="text-align: left;">year</td>
<td style="text-align: right;">2013.0</td>
<td style="text-align: right;">2014.00</td>
<td style="text-align: right;">2015.0</td>
<td style="text-align: right;">2016.0</td>
<td style="text-align: right;">2017.0</td>
<td style="text-align: right;">2018.00</td>
<td style="text-align: right;">2019.0</td>
<td style="text-align: right;">2020</td>
<td style="text-align: right;">2021</td>
<td style="text-align: right;">2022.00</td>
<td style="text-align: right;">2023.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">recruitment_1000s</td>
<td style="text-align: right;">37796.8</td>
<td style="text-align: right;">7268.36</td>
<td style="text-align: right;">27643.7</td>
<td style="text-align: right;">66059.4</td>
<td style="text-align: right;">13137.7</td>
<td style="text-align: right;">3955.65</td>
<td style="text-align: right;">13835.9</td>
<td style="text-align: right;">154839</td>
<td style="text-align: right;">208277</td>
<td style="text-align: right;">9122.34</td>
<td style="text-align: right;">18302.3</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</section>
</section>
<section id="management" class="level4" data-number="1.2.1.5">
<h4 data-number="1.2.1.5" class="anchored" data-anchor-id="management"><span class="header-section-number">1.2.1.5</span> Management</h4>
<ul>
<li><p><code>FMSY</code>: Fishing mortality rate that produces the maximum sustainable yield. Given the information available in the stock assessments, and as done in other publications, we could use the <code>Exploitation Rate Corresponding to SPR MSY</code> as proxy of <code>FMSY</code>. We can get this value from page xii, table v (<span class="citation" data-cites="johnson2023sablefish">Johnson, Wetzel, and Tolimieri (<a href="references.html#ref-johnson2023sablefish" role="doc-biblioref">2023</a>)</span>). The <code>Exploitation Rate Corresponding to SPR MSY</code>, and <code>lower</code> and <code>upper</code> intervals are 0.069, 0.057 and 0.082, respectively. These values will be assigned to <code>FMSY</code>, <code>FMSYlower</code> and <code>FMSYupper</code>, DISPLACE parameters. (This value is also given to <code>F_target</code>).</p></li>
<li><p><code>B_trigger</code>: The biomass trigger is a reference point that initiates specific management actions when the biomass of a fish stock falls below or exceeds a certain threshold. Currently, a trigger of 40%* for groundfish and 25% for flatfish (including Dover sole) is used. When biomass falls below these thresholds, a fishing mortality rate more conservative than FMSY is applied. However, we still need to define how DISPLACE captures this and determine which mortality rate applies under such events. Additionally, it is important to define the units used—whether as a percentage or in per one format. Pending further discussion with Bastardie, we will include no management triggers (<code>B_trigger = 0</code>). <span style="color:orange; font-weight:bold;">TO DISCUSS</span></p></li>
<li><p><code>mls</code> and <code>mls_cat</code>: minimum landing size (the smallest legal size at which a fish can be caught, kept, and sold) and the corresponding DISPLACE size category. There is no minimum individual size for DTS. Thus both values will be 0.</p></li>
<li><p><code>tac_tons</code>: Total Allowable Catch. It represents the maximum quantity of fish that can be legally harvested from a particular fishery over a specified period. For the U.S. fisheries management system this parameter corresponds to the Annual Catch Limit (ACL). We can get ACL from the <a href="https://www.pcouncil.org/harvest-specifications-regulations-and-seasons/">Groundfish biennial harvest specifications and management measures</a> of the Pacific Fishery Management Council (<span class="citation" data-cites="PFMC2022">Pacific Fishery Management Council (<a href="references.html#ref-PFMC2022" role="doc-biblioref">2022</a>)</span>, <span class="citation" data-cites="PFMC2020">Pacific Fishery Management Council (<a href="references.html#ref-PFMC2020" role="doc-biblioref">2020</a>)</span>, <span class="citation" data-cites="PFMC2016">Pacific Fishery Management Council (<a href="references.html#ref-PFMC2016" role="doc-biblioref">2016</a>)</span>).</p>
<p>Different ACL (mT) values are defined for each year as shown in <a href="#tbl-allocation-data">Table&nbsp;<span>1.3</span></a>. For some of our species of interest, there are also distinct values depending on the zones split by a specific latitude. For simplicity, we will aggregate these values to obtain a unique TAC estimate without distinguishing by zone. Since DISPLACE does not allow changes to values across years simulated, we will use an average value across multiple years.</p></li>
</ul>
<div class="cell" data-hash="populations_cache/html/tbl-allocation-data_205afe50a6a28751f013818c98750b23">
<div class="cell-output-display">
<div id="tbl-allocation-data" class="anchored">
<table class="table table-sm table-striped small">
<caption>Table&nbsp;1.3: Catch allocation for commercial fishing based.</caption>
<colgroup>
<col style="width: 20%">
<col style="width: 11%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Stock_Complex</th>
<th style="text-align: left;">Area</th>
<th style="text-align: right;">ACL_2017</th>
<th style="text-align: right;">ACL_2018</th>
<th style="text-align: right;">ACL_2019</th>
<th style="text-align: right;">ACL_2020</th>
<th style="text-align: right;">ACL_2021</th>
<th style="text-align: right;">ACL_2022</th>
<th style="text-align: right;">ACL_2023</th>
<th style="text-align: right;">ACL_2024</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Dover Sole</td>
<td style="text-align: left;">CW</td>
<td style="text-align: right;">50000</td>
<td style="text-align: right;">50000</td>
<td style="text-align: right;">50000</td>
<td style="text-align: right;">50000</td>
<td style="text-align: right;">50000</td>
<td style="text-align: right;">50000</td>
<td style="text-align: right;">50000</td>
<td style="text-align: right;">50000</td>
</tr>
<tr class="even">
<td style="text-align: left;">Longspine Thornyhead</td>
<td style="text-align: left;">N of 34°27’</td>
<td style="text-align: right;">2894</td>
<td style="text-align: right;">2747</td>
<td style="text-align: right;">2603</td>
<td style="text-align: right;">2470</td>
<td style="text-align: right;">2634</td>
<td style="text-align: right;">2452</td>
<td style="text-align: right;">2295</td>
<td style="text-align: right;">2162</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Longspine Thornyhead</td>
<td style="text-align: left;">S of 34°27’</td>
<td style="text-align: right;">914</td>
<td style="text-align: right;">867</td>
<td style="text-align: right;">822</td>
<td style="text-align: right;">780</td>
<td style="text-align: right;">832</td>
<td style="text-align: right;">774</td>
<td style="text-align: right;">725</td>
<td style="text-align: right;">683</td>
</tr>
<tr class="even">
<td style="text-align: left;">Shortspine Thornyhead</td>
<td style="text-align: left;">N of 34°27’</td>
<td style="text-align: right;">1713</td>
<td style="text-align: right;">1698</td>
<td style="text-align: right;">1683</td>
<td style="text-align: right;">1669</td>
<td style="text-align: right;">1428</td>
<td style="text-align: right;">1393</td>
<td style="text-align: right;">1359</td>
<td style="text-align: right;">1328</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Shortspine Thornyhead</td>
<td style="text-align: left;">S of 34°27’</td>
<td style="text-align: right;">906</td>
<td style="text-align: right;">898</td>
<td style="text-align: right;">890</td>
<td style="text-align: right;">883</td>
<td style="text-align: right;">756</td>
<td style="text-align: right;">737</td>
<td style="text-align: right;">719</td>
<td style="text-align: right;">702</td>
</tr>
<tr class="even">
<td style="text-align: left;">Sablefish</td>
<td style="text-align: left;">N of 36°</td>
<td style="text-align: right;">6041</td>
<td style="text-align: right;">6299</td>
<td style="text-align: right;">5606</td>
<td style="text-align: right;">5723</td>
<td style="text-align: right;">6479</td>
<td style="text-align: right;">6172</td>
<td style="text-align: right;">8486</td>
<td style="text-align: right;">7780</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Sablefish</td>
<td style="text-align: left;">S of 36°</td>
<td style="text-align: right;">1075</td>
<td style="text-align: right;">1120</td>
<td style="text-align: right;">1990</td>
<td style="text-align: right;">2032</td>
<td style="text-align: right;">2312</td>
<td style="text-align: right;">2203</td>
<td style="text-align: right;">2338</td>
<td style="text-align: right;">2143</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>Data available at:</p>
<ul>
<li><p>Groundfish Harvest Specifications and Management Measures for 2023-2024 (including Amendment 30). See table 1-2 (<span class="citation" data-cites="PFMC2022">Pacific Fishery Management Council (<a href="references.html#ref-PFMC2022" role="doc-biblioref">2022</a>)</span>).</p></li>
<li><p>Groundfish Harvest Specifications and Management Measures for 2021-2022 (including Amendment 29). See table 2-1 (<span class="citation" data-cites="PFMC2020">Pacific Fishery Management Council (<a href="references.html#ref-PFMC2020" role="doc-biblioref">2020</a>)</span>).</p></li>
<li><p>Groundfish Harvest Specifications and Management Measures for 2019-2020. See table 2-1 (<span class="citation" data-cites="PFMC2018">Pacific Fishery Management Council (<a href="references.html#ref-PFMC2018" role="doc-biblioref">2018</a>)</span>).</p></li>
<li><p>2017-2018 Harvest Specifications and Management Measures (including Amendment 27). See table 2-1 (<span class="citation" data-cites="PFMC2016">Pacific Fishery Management Council (<a href="references.html#ref-PFMC2016" role="doc-biblioref">2016</a>)</span>).</p></li>
</ul>
<p>For Sablefish we get the following:</p>
<div class="cell" data-hash="populations_cache/html/unnamed-chunk-22_245ecd02ff3ba7a99a6998b9ae35a430">
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<colgroup>
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">ACL_2017</th>
<th style="text-align: right;">ACL_2018</th>
<th style="text-align: right;">ACL_2019</th>
<th style="text-align: right;">ACL_2020</th>
<th style="text-align: right;">ACL_2021</th>
<th style="text-align: right;">ACL_2022</th>
<th style="text-align: right;">ACL_2023</th>
<th style="text-align: right;">ACL_2024</th>
<th style="text-align: right;">mean_ACL</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">7116</td>
<td style="text-align: right;">7419</td>
<td style="text-align: right;">7596</td>
<td style="text-align: right;">7755</td>
<td style="text-align: right;">8791</td>
<td style="text-align: right;">8375</td>
<td style="text-align: right;">10824</td>
<td style="text-align: right;">9923</td>
<td style="text-align: right;">8474.875</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Alternatively, we could also use information on the proportion of the ACL that has been allocated to commercial fishing, which may be more representative of what our simulated vessels are allowed to catch.</p>
<ul>
<li><code>TAC_percent</code>: This variable represents the maximum allowed change in TAC from one year to the next. In other words, TAC in year $year_{y+1} $ cannot differ by more than <span class="math inline">\(XX\%\)</span> of TAC in year $year_y $. Using the ACL values from above, we calculate an average year-to-year change of 5.4688129%. Values within <code>Stock_biological_traits.csv</code> are expressed in per one. (This value is also applied to <code>F_percent</code>). Discuss whether it can express negative change.</li>
</ul>
<ul>
<li><code>fbar_assessment</code>: Average annual fishing mortalities, calculated as the mean of the F at a range of ages (fully exploited age classes). The available assessments do not estimate any values of fishing mortality. Alternatively, we could use relative fishing intensity or exploitation rate as a proxy. Table iv from <span class="citation" data-cites="johnson2023sablefish">Johnson, Wetzel, and Tolimieri (<a href="references.html#ref-johnson2023sablefish" role="doc-biblioref">2023</a>)</span> contains exploitation rate time series, which we can average to get our estimate of interest. Exploitation rate is just a slightly different conceptualization of fishing mortality. It represents a proportion rather than a rate. By averaging the exploitation rates (<a href="#tbl-sablefish-fbar">Table&nbsp;<span>1.4</span></a>), we get an <code>fbar_assessment</code> value of 0.0208. <span style="color:orange; font-weight:bold;">TO DISCUSS</span></li>
</ul>
<div class="cell" data-hash="populations_cache/html/tbl-sablefish-fbar_226818daa070482e95430cb1532c68c9">
<div class="cell-output-display">
<div id="tbl-sablefish-fbar" class="anchored">
<table class="table table-sm table-striped small">
<caption>Table&nbsp;1.4: Exploitation rates time series for Sablefish, used as a proxy of fishing mortality.</caption>
<colgroup>
<col style="width: 16%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
</colgroup>
<tbody>
<tr class="odd">
<td style="text-align: left;">year</td>
<td style="text-align: right;">2013.000</td>
<td style="text-align: right;">2014.000</td>
<td style="text-align: right;">2015.000</td>
<td style="text-align: right;">2016.000</td>
<td style="text-align: right;">2017.000</td>
<td style="text-align: right;">2018.000</td>
<td style="text-align: right;">2019.000</td>
<td style="text-align: right;">2020.000</td>
<td style="text-align: right;">2021.000</td>
<td style="text-align: right;">2022.000</td>
</tr>
<tr class="even">
<td style="text-align: left;">exploitation_rate</td>
<td style="text-align: right;">0.018</td>
<td style="text-align: right;">0.019</td>
<td style="text-align: right;">0.023</td>
<td style="text-align: right;">0.025</td>
<td style="text-align: right;">0.024</td>
<td style="text-align: right;">0.023</td>
<td style="text-align: right;">0.022</td>
<td style="text-align: right;">0.014</td>
<td style="text-align: right;">0.017</td>
<td style="text-align: right;">0.023</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<ul>
<li><code>fbar_age_min</code> and <code>fbar_age_max</code>: these refer to the minimum and maximum ages used to calculate the mean fishing mortality rate (fbar_assessment). These correspond to the youngest and oldest age classes included in the calculation. <span style="color:red; font-weight:bold;">MISSING</span></li>
</ul>
<p>The assessments do not include such information, but we can infer it from the range of ages selected by the fishery based on gear selectivity. These can be used as the range of ages over which F is averaged. From the estimated selectivity in the first two plots in Figure 33 of <span class="citation" data-cites="johnson2023sablefish">Johnson, Wetzel, and Tolimieri (<a href="references.html#ref-johnson2023sablefish" role="doc-biblioref">2023</a>)</span>, we can see that all ages are included. Therefore, fbar_age_min will be 0, and fbar_age_max will correspond to X.</p>
<div class="cell" data-hash="populations_cache/html/unnamed-chunk-27_8fd52cba3b98d7d71f138bc42faad109">
<div class="cell-output-display">
<table data-quarto-postprocess="true" class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Parameter</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Value</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Reference</th>
</tr>
</thead>
<tbody>
<tr class="odd" data-grouplength="5">
<td colspan="3" style="border-bottom: 1px solid"><strong>Somatic growth</strong></td>
</tr>
<tr class="even">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">Linf</td>
<td style="text-align: left;">58.6210501</td>
<td style="text-align: left;">@johnson2023sablefish</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">CV_Linf</td>
<td style="text-align: left;">0.0905000</td>
<td style="text-align: left;">@johnson2023sablefish</td>
</tr>
<tr class="even">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">K</td>
<td style="text-align: left;">0.3740000</td>
<td style="text-align: left;">@johnson2023sablefish</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">t0</td>
<td style="text-align: left;">-1.2800000</td>
<td style="text-align: left;">@head2014sablefish</td>
</tr>
<tr class="even">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">CV_recru</td>
<td style="text-align: left;">2.4696816</td>
<td style="text-align: left;">@johnson2023sablefish</td>
</tr>
<tr class="odd" data-grouplength="2">
<td colspan="3" style="border-bottom: 1px solid"><strong>Length-weight relationship</strong></td>
</tr>
<tr class="even">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">a</td>
<td style="text-align: left;">0.0000033</td>
<td style="text-align: left;">@haltuch2019sablefish</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">b</td>
<td style="text-align: left;">3.2713600</td>
<td style="text-align: left;">@haltuch2019sablefish</td>
</tr>
<tr class="even" data-grouplength="3">
<td colspan="3" style="border-bottom: 1px solid"><strong>Maturity</strong></td>
</tr>
<tr class="odd">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">L50</td>
<td style="text-align: left;">52.6606373</td>
<td style="text-align: left;">@head2014sablefish, @haltuch2019sablefish</td>
</tr>
<tr class="even">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">mat_cat</td>
<td style="text-align: left;">9.0000000</td>
<td style="text-align: left;">@head2014sablefish, @haltuch2019sablefish</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">r_age</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">@head2014sablefish</td>
</tr>
<tr class="even" data-grouplength="6">
<td colspan="3" style="border-bottom: 1px solid"><strong>Recruitment</strong></td>
</tr>
<tr class="odd">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">ssb_assessment</td>
<td style="text-align: left;">86995.0000000</td>
<td style="text-align: left;">@johnson2023sablefish</td>
</tr>
<tr class="even">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">h</td>
<td style="text-align: left;">0.7000000</td>
<td style="text-align: left;">@johnson2023sablefish</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">R0</td>
<td style="text-align: left;">19453.9000000</td>
<td style="text-align: left;">@johnson2023sablefish</td>
</tr>
<tr class="even">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">SPR_0</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">alpha</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">beta</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="odd" data-grouplength="11">
<td colspan="3" style="border-bottom: 1px solid"><strong>Management</strong></td>
</tr>
<tr class="even">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">FMSY</td>
<td style="text-align: left;">0.0690000</td>
<td style="text-align: left;">@johnson2023sablefish</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">FMSYlower</td>
<td style="text-align: left;">0.0570000</td>
<td style="text-align: left;">@johnson2023sablefish</td>
</tr>
<tr class="even">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">FMSYupper</td>
<td style="text-align: left;">0.0820000</td>
<td style="text-align: left;">@johnson2023sablefish</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">B_trigger</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">mls</td>
<td style="text-align: left;">0.0000000</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">mls_cat</td>
<td style="text-align: left;">0.0000000</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">tac_tons</td>
<td style="text-align: left;">8474.8750000</td>
<td style="text-align: left;">@PFMC2022</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">TAC_percent</td>
<td style="text-align: left;">0.0546881</td>
<td style="text-align: left;">@PFMC2022</td>
</tr>
<tr class="even">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">fbar_assessment</td>
<td style="text-align: left;">0.0208000</td>
<td style="text-align: left;">@johnson2023sablefish</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">fbar_age_min</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">fbar_age_max</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
</tr>
</tbody>
</table>


</div>
</div>
</section>
</section>
<section id="dover-sole" class="level3" data-number="1.2.2">
<h3 data-number="1.2.2" class="anchored" data-anchor-id="dover-sole"><span class="header-section-number">1.2.2</span> Dover Sole</h3>
<p>(<em>Microstomus pacificus</em>) (FAO code MIP)</p>
<hr>
<section id="somatic-growth-1" class="level4" data-number="1.2.2.1">
<h4 data-number="1.2.2.1" class="anchored" data-anchor-id="somatic-growth-1"><span class="header-section-number">1.2.2.1</span> Somatic growth</h4>
<ul>
<li><code>Linf</code>: We will derive <code>Linf</code> from the Schnute parameters included in the stock assessment (<a href="#tbl-doversole-Schnute">Table&nbsp;<span>1.5</span></a>).</li>
</ul>
<div class="cell" data-hash="populations_cache/html/tbl-doversole-Schnute_2211c220681444cae261e02657f6c886">
<div class="cell-output-display">
<div id="tbl-doversole-Schnute" class="anchored">
<table class="table table-sm table-striped small">
<caption>Table&nbsp;1.5: Schnute and von Bertalanffy growth parameters for Dover sole from table 21 and 26 of the stock assessment.</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Parameter</th>
<th style="text-align: right;">Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">L at Amin Fem GP 1</td>
<td style="text-align: right;">7.994</td>
</tr>
<tr class="even">
<td style="text-align: left;">L at Amax Fem GP 1</td>
<td style="text-align: right;">48.052</td>
</tr>
<tr class="odd">
<td style="text-align: left;">VonBert K Fem GP 1</td>
<td style="text-align: right;">0.132</td>
</tr>
<tr class="even">
<td style="text-align: left;">Length at Amin - Male</td>
<td style="text-align: right;">10.350</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Length at Amax - Male</td>
<td style="text-align: right;">41.970</td>
</tr>
<tr class="even">
<td style="text-align: left;">Von Bert. k - Male</td>
<td style="text-align: right;">0.140</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>For females, <span class="math inline">\(L_1\)</span> correspond to <code>L at Amin Fem GP 1</code> (7.994) and <code>Length at Amin - Female</code> (7.990), and <span class="math inline">\(L_2\)</span> to <code>L at Amax Fem GP 1</code> (48.052) and <code>Length at Amax - Female</code> (48.050), in tables 21 and 26. Male values correspond to <code>Length at Amin - Male</code> (10.35) and <code>Length at Amax - Male</code> (41.97) from table 26 (<span class="citation" data-cites="wetzel2021doversole_benchmark">Wetzel and Berger (<a href="references.html#ref-wetzel2021doversole_benchmark" role="doc-biblioref">2021</a>)</span>). Male values in table 21 are wrong. <span class="math inline">\(K\)</span> corresponds to 0.117 for females and 0.106 for males from page 20 (<span class="citation" data-cites="wetzel2021doversole_benchmark">Wetzel and Berger (<a href="references.html#ref-wetzel2021doversole_benchmark" role="doc-biblioref">2021</a>)</span>). As for <code>t1</code> and <code>t2</code>, these correspond to the minimum age and maximum age for calculations 1 and 60, respectively as described in table 20 on model specifications (<span class="citation" data-cites="wetzel2021doversole_benchmark">Wetzel and Berger (<a href="references.html#ref-wetzel2021doversole_benchmark" role="doc-biblioref">2021</a>)</span>).</p>
<p>Calculating female (48.0922894) and male (42.0309144) values independently and then averaging them yields a <code>Linf</code> of 45.0616019.</p>
<p>Page 20 of the <span class="citation" data-cites="wetzel2021doversole_benchmark">Wetzel and Berger (<a href="references.html#ref-wetzel2021doversole_benchmark" role="doc-biblioref">2021</a>)</span> assessment contains different <code>Linf</code> values of 48.5 and 43.1 for females and males, respectively. However, these values were initially estimated externally and used as starting parameter values within the base model before estimating each parameter. While we won’t consider them here, we can use them as a reference.</p>
<ul>
<li><p><code>CV_Linf</code>: For females we can use <code>CV old Fem GP 1</code> and <code>CV old - Female</code> with a value of 0.080 in table 21 and table 26, respectively. For <code>males CV old - Male</code> 0.080 in table 26 (<span class="citation" data-cites="wetzel2021doversole_benchmark">Wetzel and Berger (<a href="references.html#ref-wetzel2021doversole_benchmark" role="doc-biblioref">2021</a>)</span>).</p></li>
<li><p><code>K</code>: 0.117 for females and 0.106 for males from page 20 (<span class="citation" data-cites="wetzel2021doversole_benchmark">Wetzel and Berger (<a href="references.html#ref-wetzel2021doversole_benchmark" role="doc-biblioref">2021</a>)</span>). Mean value used 0.1115.</p></li>
<li><p><code>t0</code>: Considering that the stock assessment express growth using Schnute parameters, we’ll derive <span class="math inline">\(t_0\)</span> from Schnute parameters in <span class="citation" data-cites="wetzel2021doversole_benchmark">Wetzel and Berger (<a href="references.html#ref-wetzel2021doversole_benchmark" role="doc-biblioref">2021</a>)</span>.</p></li>
</ul>
<p>This yields a <code>t0</code> of -1.666896, which we will use.</p>
<p>For reference, MARLIN modeling framework used -2.66 for females and -1.97 for males (mean value of -2.315) from page 354 (<span class="citation" data-cites="stockhausen2005doversole">Stockhausen et al. (<a href="references.html#ref-stockhausen2005doversole" role="doc-biblioref">2005</a>)</span>). However, this publication assessed Alaskan populations. <span style="color:orange; font-weight:bold;">TO DISCUSS</span></p>
<ul>
<li><code>CV_recru</code>: On pages viii and 32 of <span class="citation" data-cites="wetzel2021doversole_benchmark">Wetzel and Berger (<a href="references.html#ref-wetzel2021doversole_benchmark" role="doc-biblioref">2021</a>)</span>, recruitment is defined based on a fixed assumption about recruitment variability (<span class="math inline">\(\sigma R = 0.35\)</span>). Applying the expression used above, we establish a CV of approximately 0.3609974.</li>
</ul>
</section>
<section id="length-weight-relationship-1" class="level4" data-number="1.2.2.2">
<h4 data-number="1.2.2.2" class="anchored" data-anchor-id="length-weight-relationship-1"><span class="header-section-number">1.2.2.2</span> Length-weight relationship</h4>
<ul>
<li><p><code>a</code>: Female 2.97e-06 and male 2.6e-06 from page 19 (<span class="citation" data-cites="wetzel2021doversole_benchmark">Wetzel and Berger (<a href="references.html#ref-wetzel2021doversole_benchmark" role="doc-biblioref">2021</a>)</span>). Mean value used 2.785^{-6}.</p></li>
<li><p><code>b</code>: Female 3.33 and male 3.37 from page 19 (<span class="citation" data-cites="wetzel2021doversole_benchmark">Wetzel and Berger (<a href="references.html#ref-wetzel2021doversole_benchmark" role="doc-biblioref">2021</a>)</span>). Mean value used 3.35.</p></li>
</ul>
</section>
<section id="maturity-1" class="level4" data-number="1.2.2.3">
<h4 data-number="1.2.2.3" class="anchored" data-anchor-id="maturity-1"><span class="header-section-number">1.2.2.3</span> Maturity</h4>
<ul>
<li><p><code>L50</code>: 32.8 cm from page 18 and 32.840 from <code>Mat50% Fem GP 1</code> in table 21 (<span class="citation" data-cites="wetzel2021doversole_benchmark">Wetzel and Berger (<a href="references.html#ref-wetzel2021doversole_benchmark" role="doc-biblioref">2021</a>)</span>). Here again we can use the proportion of <code>L50</code> to <code>Linf</code> observed in females to determine male’s <code>L50</code>. With it we get a value of 28.6834013 cm for males. Mean value across Male and Female used 30.7617007. (This value is also given to the parameter <code>mat</code>)</p></li>
<li><p><code>mat_cat</code>: This corresponds to the maturity size DISPLACE category at the L50. For an <code>L50</code> of 30.7617007 cm is 5.</p></li>
<li><p><code>r_age</code>: Using <code>A50</code> as a reference, value of 7 years from page 140 (<span class="citation" data-cites="hunter1990doversole">Hunter et al. (<a href="references.html#ref-hunter1990doversole" role="doc-biblioref">1990</a>)</span>) (Not used in DISPLACE, but included in the input files as a reference). Set value to <code>NA</code> to prevent any errors.</p></li>
<li><p><code>ssb_assessment</code>: Spawning Biomass value for year 2011 of 221913 mt, page v, table ii (<span class="citation" data-cites="wetzel2021doversole_benchmark">Wetzel and Berger (<a href="references.html#ref-wetzel2021doversole_benchmark" role="doc-biblioref">2021</a>)</span>). There are no values prior to 2011. (Not used in DISPLACE, but included in the input files as a reference)</p></li>
</ul>
</section>
<section id="recruitment" class="level4" data-number="1.2.2.4">
<h4 data-number="1.2.2.4" class="anchored" data-anchor-id="recruitment"><span class="header-section-number">1.2.2.4</span> Recruitment</h4>
<p>Parameters needed to calculate <code>alpha</code> and <code>beta</code>:</p>
<ul>
<li><span class="math inline">\(h\)</span>: steepness is 0.8 as described in pages viii, xii and xiii (<span class="citation" data-cites="wetzel2021doversole_benchmark">Wetzel and Berger (<a href="references.html#ref-wetzel2021doversole_benchmark" role="doc-biblioref">2021</a>)</span>).</li>
<li><span class="math inline">\(R_0\)</span>: value is 213096 from table v and table 23 (<span class="citation" data-cites="wetzel2021doversole_benchmark">Wetzel and Berger (<a href="references.html#ref-wetzel2021doversole_benchmark" role="doc-biblioref">2021</a>)</span>).</li>
<li><span class="math inline">\(SPR_0\)</span>: In Table 2 we can find several SPR values, but none for the unfished equilibrium (<span class="citation" data-cites="wetzel2021doversole_benchmark">Wetzel and Berger (<a href="references.html#ref-wetzel2021doversole_benchmark" role="doc-biblioref">2021</a>)</span>). <span style="color:red; font-weight:bold;">MISSING</span></li>
</ul>
<ul>
<li><p><code>fixed recruitment</code>:</p>
<p>From Table iii in <span class="citation" data-cites="wetzel2021doversole_benchmark">Wetzel and Berger (<a href="references.html#ref-wetzel2021doversole_benchmark" role="doc-biblioref">2021</a>)</span> (<a href="#tbl-doversole-recruitment">Table&nbsp;<span>1.6</span></a>), we get a mean recruitment value of 2.0170473^{5} thousand individuals.</p>
<p><strong>NOTE: For Sablefish and Longspine, these values are provided in thousands and millions (pages vii and 7, respectively). However, for Dover Sole and Shortspine, the values do not appear to be in any unit scaling, which make them abnormally low (pages viii and vi, respectively). The recruitment estimates seem too low compared to the others. Could it be that these values are actually expressed in thousands, and this is just a typo in the report? Actually, in both cases the figures of estimated time series of age-0 recruits are expressed in 1000s. I’ve already come across other typos, such as the length-weight relationship units, before. I guess these are most likely expressed in 1000s although the text does not specifies it. TO CONFIRM.</strong></p></li>
</ul>
<div class="cell" data-hash="populations_cache/html/tbl-doversole-recruitment_afb039d21514255c3e986983494564c3">
<div class="cell-output-display">
<div id="tbl-doversole-recruitment" class="anchored">
<table class="table table-sm table-striped small">
<caption>Table&nbsp;1.6: Estimated recent trend in recruitment (1,000s) for Dover Sole.</caption>
<colgroup>
<col style="width: 18%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
</colgroup>
<tbody>
<tr class="odd">
<td style="text-align: left;">year</td>
<td style="text-align: right;">2011</td>
<td style="text-align: right;">2012</td>
<td style="text-align: right;">2013</td>
<td style="text-align: right;">2014</td>
<td style="text-align: right;">2015</td>
<td style="text-align: right;">2016</td>
<td style="text-align: right;">2017</td>
<td style="text-align: right;">2018</td>
<td style="text-align: right;">2019</td>
<td style="text-align: right;">2020</td>
<td style="text-align: right;">2021</td>
</tr>
<tr class="even">
<td style="text-align: left;">recruitment_1000s</td>
<td style="text-align: right;">204214</td>
<td style="text-align: right;">238648</td>
<td style="text-align: right;">161941</td>
<td style="text-align: right;">166317</td>
<td style="text-align: right;">199178</td>
<td style="text-align: right;">205309</td>
<td style="text-align: right;">206028</td>
<td style="text-align: right;">208863</td>
<td style="text-align: right;">209235</td>
<td style="text-align: right;">209423</td>
<td style="text-align: right;">209596</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</section>
<section id="management-1" class="level4" data-number="1.2.2.5">
<h4 data-number="1.2.2.5" class="anchored" data-anchor-id="management-1"><span class="header-section-number">1.2.2.5</span> Management</h4>
<ul>
<li><p><code>FMSY</code>: Using the <code>Exploitation Rate Corresponding to SPR MSY</code> as a proxy for <code>FMSY</code>, we can get the values for <code>FMSY</code>, <code>FMSYlower</code>, and <code>FMSYupper</code> as 0.13, 0.12, and 0.13, respectively, from on Table V and Table 23 (<span class="citation" data-cites="wetzel2021doversole_benchmark">Wetzel and Berger (<a href="references.html#ref-wetzel2021doversole_benchmark" role="doc-biblioref">2021</a>)</span>). (This value is also used as the <code>F_target</code>.)</p></li>
<li><p><code>B_trigger</code>: The biomass trigger is a reference point that initiates specific management actions when the biomass of a fish stock falls below or exceeds a certain threshold. Currently, there is a trigger of 40% for groundfish and 2% for flatfish. We still need to define the actions that this trigger and to what parameter this percentage applies. <span style="color:red; font-weight:bold;">MISSING</span> <strong>NOTE: How is this input into DISPLACE—percentage or per unit? How are the actions defined?</strong></p></li>
<li><p><code>B_trigger</code>: Currently, a trigger <strong>25%</strong> for flatfish (including Dover sole) is used. We still need to define how DISPLACE uses such parameter. In the meantime we won’t include any management triggers (<code>B_trigger = 0</code>). <span style="color:orange; font-weight:bold;">TO DISCUSS</span></p></li>
<li><p><code>mls</code> and <code>mls_cat</code>: There is no minimum landing size for DTS. Thus, both values will be 0.</p></li>
<li><p><code>tac_tons</code>: based on table <a href="#tbl-allocation-data">Table&nbsp;<span>1.3</span></a>, For Dover Sole we get the following:</p></li>
</ul>
<div class="cell" data-hash="populations_cache/html/unnamed-chunk-39_43cf20b482d85b5e11fc258e65b6b58a">
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<colgroup>
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">ACL_2017</th>
<th style="text-align: right;">ACL_2018</th>
<th style="text-align: right;">ACL_2019</th>
<th style="text-align: right;">ACL_2020</th>
<th style="text-align: right;">ACL_2021</th>
<th style="text-align: right;">ACL_2022</th>
<th style="text-align: right;">ACL_2023</th>
<th style="text-align: right;">ACL_2024</th>
<th style="text-align: right;">mean_ACL</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">50000</td>
<td style="text-align: right;">50000</td>
<td style="text-align: right;">50000</td>
<td style="text-align: right;">50000</td>
<td style="text-align: right;">50000</td>
<td style="text-align: right;">50000</td>
<td style="text-align: right;">50000</td>
<td style="text-align: right;">50000</td>
<td style="text-align: right;">50000</td>
</tr>
</tbody>
</table>
</div>
</div>
<ul>
<li><p><code>TAC_percent</code>: This variable represents the maximum allowed change (%) in TAC from one year to the next. Using the ACL values, we calculate an average year-to-year change of 0%. Values within <code>Stock_biological_traits.csv</code> are expressed in per one. (This value is also applied to <code>F_percent</code>.)</p></li>
<li><p><code>fbar_assessment</code>: Average annual fishing mortalities, calculated as the mean of the F at a range of ages (fully exploited age classes). <span style="color:red; font-weight:bold;">MISSING</span></p></li>
</ul>
<ul>
<li><code>fbar_assessment</code>: Using the exploitation rate from Table iv (<span class="citation" data-cites="wetzel2021doversole_benchmark">Wetzel and Berger (<a href="references.html#ref-wetzel2021doversole_benchmark" role="doc-biblioref">2021</a>)</span>) as a proxy for fishing mortality (<a href="#tbl-doversole-fbar">Table&nbsp;<span>1.7</span></a>), we get a value of 0.015. <span style="color:orange; font-weight:bold;">TO DISCUSS</span></li>
</ul>
<div class="cell" data-hash="populations_cache/html/tbl-doversole-fbar_833f84712e5d218052a35aef51c775ad">
<div class="cell-output-display">
<div id="tbl-doversole-fbar" class="anchored">
<table class="table table-sm table-striped small">
<caption>Table&nbsp;1.7: Exploitation rates time series for Dover Sole, used as a proxy of fishing mortality.</caption>
<colgroup>
<col style="width: 18%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
</colgroup>
<tbody>
<tr class="odd">
<td style="text-align: left;">year</td>
<td style="text-align: right;">2011.00</td>
<td style="text-align: right;">2012.00</td>
<td style="text-align: right;">2013.00</td>
<td style="text-align: right;">2014.00</td>
<td style="text-align: right;">2015.00</td>
<td style="text-align: right;">2016.00</td>
<td style="text-align: right;">2017.00</td>
<td style="text-align: right;">2018.00</td>
<td style="text-align: right;">2019.00</td>
<td style="text-align: right;">2020.00</td>
</tr>
<tr class="even">
<td style="text-align: left;">exploitation_rate</td>
<td style="text-align: right;">0.02</td>
<td style="text-align: right;">0.02</td>
<td style="text-align: right;">0.02</td>
<td style="text-align: right;">0.01</td>
<td style="text-align: right;">0.01</td>
<td style="text-align: right;">0.02</td>
<td style="text-align: right;">0.02</td>
<td style="text-align: right;">0.01</td>
<td style="text-align: right;">0.01</td>
<td style="text-align: right;">0.01</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<ul>
<li><code>fbar_age_min</code> and <code>fbar_age_max</code>: these refer to the minimum and maximum ages used to calculate the mean fishing mortality rate (<code>fbar_assessment</code>). These correspond to the youngest and oldest age classes included in the calculation. <span style="color:red; font-weight:bold;">MISSING</span></li>
</ul>
<p>The assessments do not include such information, but we can infer it from the range of ages selected by the fishery based on gear selectivity. These can be used as the range of ages over which F is averaged. From the estimated selectivity in the plot depicting CA selectivity in Figure 85 of <span class="citation" data-cites="wetzel2021doversole_benchmark">Wetzel and Berger (<a href="references.html#ref-wetzel2021doversole_benchmark" role="doc-biblioref">2021</a>)</span>, we can see that fishes are not selected below ~25cm which, applying Bertalanffy growth function would correspond to an age of X.</p>
<div class="cell" data-hash="populations_cache/html/unnamed-chunk-44_ff467c7496d3fedf2a048ac59cbe6a5c">
<div class="cell-output-display">
<table class="table table-striped table-hover table-sm small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th" style="text-align: left; font-weight: bold;">Parameter</th>
<th data-quarto-table-cell-role="th" style="text-align: left; font-weight: bold;">Value</th>
<th data-quarto-table-cell-role="th" style="text-align: left; font-weight: bold;">Reference</th>
</tr>
</thead>
<tbody>
<tr class="odd" data-grouplength="5">
<td colspan="3" style="border-bottom: 1px solid"><strong>Somatic growth</strong></td>
</tr>
<tr class="even">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">Linf</td>
<td style="text-align: left;">4.506160e+01</td>
<td style="text-align: left;">@wetzel2021doversole_benchmark</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">CV_Linf</td>
<td style="text-align: left;">8.000000e-02</td>
<td style="text-align: left;">@wetzel2021doversole_benchmark</td>
</tr>
<tr class="even">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">K</td>
<td style="text-align: left;">1.115000e-01</td>
<td style="text-align: left;">@wetzel2021doversole_benchmark</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">t0</td>
<td style="text-align: left;">-2.315000e+00</td>
<td style="text-align: left;">@stockhausen2005doversole</td>
</tr>
<tr class="even">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">CV_recru</td>
<td style="text-align: left;">3.609974e-01</td>
<td style="text-align: left;">@wetzel2021doversole_benchmark</td>
</tr>
<tr class="odd" data-grouplength="2">
<td colspan="3" style="border-bottom: 1px solid"><strong>Length-weight relationship</strong></td>
</tr>
<tr class="even">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">a</td>
<td style="text-align: left;">2.800000e-06</td>
<td style="text-align: left;">@wetzel2021doversole_benchmark</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">b</td>
<td style="text-align: left;">3.350000e+00</td>
<td style="text-align: left;">@wetzel2021doversole_benchmark</td>
</tr>
<tr class="even" data-grouplength="3">
<td colspan="3" style="border-bottom: 1px solid"><strong>Maturity</strong></td>
</tr>
<tr class="odd">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">L50</td>
<td style="text-align: left;">3.076170e+01</td>
<td style="text-align: left;">@wetzel2021doversole_benchmark</td>
</tr>
<tr class="even">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">mat_cat</td>
<td style="text-align: left;">5.000000e+00</td>
<td style="text-align: left;">@wetzel2021doversole_benchmark</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">r_age</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">@hunter1990doversole</td>
</tr>
<tr class="even" data-grouplength="6">
<td colspan="3" style="border-bottom: 1px solid"><strong>Recruitment</strong></td>
</tr>
<tr class="odd">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">ssb_assessment</td>
<td style="text-align: left;">2.219130e+05</td>
<td style="text-align: left;">@wetzel2021doversole_benchmark</td>
</tr>
<tr class="even">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">h</td>
<td style="text-align: left;">8.000000e-01</td>
<td style="text-align: left;">@wetzel2021doversole_benchmark</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">R0</td>
<td style="text-align: left;">2.130960e+05</td>
<td style="text-align: left;">@wetzel2021doversole_benchmark</td>
</tr>
<tr class="even">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">SPR_0</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">alpha</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">beta</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="odd" data-grouplength="11">
<td colspan="3" style="border-bottom: 1px solid"><strong>Management</strong></td>
</tr>
<tr class="even">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">FMSY</td>
<td style="text-align: left;">1.300000e-01</td>
<td style="text-align: left;">@wetzel2021doversole_benchmark</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">FMSYlower</td>
<td style="text-align: left;">1.200000e-01</td>
<td style="text-align: left;">@wetzel2021doversole_benchmark</td>
</tr>
<tr class="even">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">FMSYupper</td>
<td style="text-align: left;">1.300000e-01</td>
<td style="text-align: left;">@wetzel2021doversole_benchmark</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">B_trigger</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">mls</td>
<td style="text-align: left;">0.000000e+00</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">mls_cat</td>
<td style="text-align: left;">0.000000e+00</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">tac_tons</td>
<td style="text-align: left;">5.000000e+04</td>
<td style="text-align: left;">@PFMC2022</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">TAC_percent</td>
<td style="text-align: left;">0.000000e+00</td>
<td style="text-align: left;">@PFMC2022</td>
</tr>
<tr class="even">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">fbar_assessment</td>
<td style="text-align: left;">1.500000e-02</td>
<td style="text-align: left;">@wetzel2021doversole_benchmark</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">fbar_age_min</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">fbar_age_max</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
</tr>
</tbody>
</table>


</div>
</div>
</section>
</section>
<section id="longspine-thornyhead" class="level3" data-number="1.2.3">
<h3 data-number="1.2.3" class="anchored" data-anchor-id="longspine-thornyhead"><span class="header-section-number">1.2.3</span> Longspine Thornyhead</h3>
<p>(<em>Sebastolobus altivelis</em>) (FAO code SJZ)</p>
<hr>
<section id="somatic-growth-2" class="level4" data-number="1.2.3.1">
<h4 data-number="1.2.3.1" class="anchored" data-anchor-id="somatic-growth-2"><span class="header-section-number">1.2.3.1</span> Somatic growth</h4>
<ul>
<li><code>Linf</code>: We will derive <code>Linf</code> from the Schnute parameters included in Table 6 of <span class="citation" data-cites="stephens2014longspine">Stephens and Taylor (<a href="references.html#ref-stephens2014longspine" role="doc-biblioref">2013</a>)</span> stock assessment.</li>
</ul>
<div class="cell" data-hash="populations_cache/html/tbl-longspine-Schnute_bdac16ca47ee9fafca941dae44004e3c">
<div class="cell-output-display">
<div id="tbl-longspine-Schnute" class="anchored">
<table class="table table-sm table-striped small">
<caption>Table&nbsp;1.8: Schnute and von Bertalanffy growth parameters for Longspine Thornyhead.</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Parameter</th>
<th style="text-align: right;">Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Length at Age 3</td>
<td style="text-align: right;">8.573000</td>
</tr>
<tr class="even">
<td style="text-align: left;">Length at Age 40</td>
<td style="text-align: right;">27.828200</td>
</tr>
<tr class="odd">
<td style="text-align: left;">VBGF K</td>
<td style="text-align: right;">0.108505</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>The stock assessment does not differentiates by sex. Thus we will use values from <a href="#tbl-longspine-Schnute">Table&nbsp;<span>1.8</span></a> directly. As for the ages, <span class="math inline">\(t_1\)</span> and <span class="math inline">\(t_2\)</span> are referenced in the same table 6, and also on page 24.</p>
<p>This yields a <code>Linf</code> of 28.1821179, smaller than the reference of 31.2 cm from table 1 in the previous assessment (<span class="citation" data-cites="fay2005longspine">Fay (<a href="references.html#ref-fay2005longspine" role="doc-biblioref">2005</a>)</span>).</p>
<ul>
<li><p><code>CV_Linf</code>: Neither the assessments by <span class="citation" data-cites="fay2005longspine">Fay (<a href="references.html#ref-fay2005longspine" role="doc-biblioref">2005</a>)</span> nor <span class="citation" data-cites="stephens2014longspine">Stephens and Taylor (<a href="references.html#ref-stephens2014longspine" role="doc-biblioref">2013</a>)</span> explicitly reference it. However, we can use the value associated with the closest length to <code>Linf</code> from Table A.1. in <span class="citation" data-cites="fay2005longspine">Fay (<a href="references.html#ref-fay2005longspine" role="doc-biblioref">2005</a>)</span>. This is 29.8 cm, with a corresponding CV of 0.04. <span style="color:orange; font-weight:bold;">TO DISCUSS</span></p></li>
<li><p><code>K</code>: value of 0.109 included in page 24, and 0.108505 form table 6 (<span class="citation" data-cites="stephens2014longspine">Stephens and Taylor (<a href="references.html#ref-stephens2014longspine" role="doc-biblioref">2013</a>)</span>). Alternative value from older assessment is 0.064 from table 1 and table 13 (<span class="citation" data-cites="fay2005longspine">Fay (<a href="references.html#ref-fay2005longspine" role="doc-biblioref">2005</a>)</span>).</p></li>
<li><p><code>t0</code>: Considering that the stock assessment express growth using Schnute parameters, we’ll derive <span class="math inline">\(t_0\)</span> from Schnute parameters in <span class="citation" data-cites="stephens2014longspine">Stephens and Taylor (<a href="references.html#ref-stephens2014longspine" role="doc-biblioref">2013</a>)</span>.</p></li>
</ul>
<p>This yields a <code>t0</code> of -0.3426386, which we will use.</p>
<p>For reference, <code>t0</code> values are quite different from one assessment to the other. For instance, <span class="citation" data-cites="fay2005longspine">Fay (<a href="references.html#ref-fay2005longspine" role="doc-biblioref">2005</a>)</span> assessment value is -2.02. This parameter across other studies and assessments seems quite variable. Table 7 in <span class="citation" data-cites="stephens2014longspine">Stephens and Taylor (<a href="references.html#ref-stephens2014longspine" role="doc-biblioref">2013</a>)</span> summarizes values across several publications, and one from 1991 also yields a <code>t0</code> of around -0.3. <span style="color:orange; font-weight:bold;">TO DISCUSS</span></p>
<ul>
<li><code>CV_recru</code>: From page 24 (<span class="citation" data-cites="fay2005longspine">Fay (<a href="references.html#ref-fay2005longspine" role="doc-biblioref">2005</a>)</span>) and table 6 (<span class="citation" data-cites="stephens2014longspine">Stephens and Taylor (<a href="references.html#ref-stephens2014longspine" role="doc-biblioref">2013</a>)</span>), <span class="math inline">\(\sigma R = 0.6\)</span>. Thus CV would be 0.6582776.</li>
</ul>
</section>
<section id="length-weight-relationship-2" class="level4" data-number="1.2.3.2">
<h4 data-number="1.2.3.2" class="anchored" data-anchor-id="length-weight-relationship-2"><span class="header-section-number">1.2.3.2</span> Length-weight relationship</h4>
<ul>
<li><p><code>a</code>: 4.3e-6 from table 13 (<span class="citation" data-cites="fay2005longspine">Fay (<a href="references.html#ref-fay2005longspine" role="doc-biblioref">2005</a>)</span>) and table 6 (<span class="citation" data-cites="stephens2014longspine">Stephens and Taylor (<a href="references.html#ref-stephens2014longspine" role="doc-biblioref">2013</a>)</span>).</p></li>
<li><p><code>b</code>: 3.352 from table 13 (<span class="citation" data-cites="fay2005longspine">Fay (<a href="references.html#ref-fay2005longspine" role="doc-biblioref">2005</a>)</span>) and table 6 (<span class="citation" data-cites="stephens2014longspine">Stephens and Taylor (<a href="references.html#ref-stephens2014longspine" role="doc-biblioref">2013</a>)</span>).</p></li>
</ul>
</section>
<section id="maturity-2" class="level4" data-number="1.2.3.3">
<h4 data-number="1.2.3.3" class="anchored" data-anchor-id="maturity-2"><span class="header-section-number">1.2.3.3</span> Maturity</h4>
<ul>
<li><p><code>L50</code>: 17.826 cm from table 6 (<span class="citation" data-cites="stephens2014longspine">Stephens and Taylor (<a href="references.html#ref-stephens2014longspine" role="doc-biblioref">2013</a>)</span>) and 17.8 from table 13 (<span class="citation" data-cites="fay2005longspine">Fay (<a href="references.html#ref-fay2005longspine" role="doc-biblioref">2005</a>)</span>), without differentiation by sex. (This value is also given to the parameter <code>mat</code>).</p></li>
<li><p><code>mat_cat</code>: This corresponds to the maturity size DISPLACE category at the L50. For an <code>L50</code> of 17.826 cm is 3.</p></li>
<li><p><code>r_age</code>: Using <code>A50</code> as a reference, value of 12 years from page 22 (<span class="citation" data-cites="fay2005longspine">Fay (<a href="references.html#ref-fay2005longspine" role="doc-biblioref">2005</a>)</span>), and range of 12-15 years from <span class="citation" data-cites="stephens2014longspine">Stephens and Taylor (<a href="references.html#ref-stephens2014longspine" role="doc-biblioref">2013</a>)</span>. Set value to <code>NA</code> to prevent any errors.</p></li>
<li><p><code>ssb_assessment</code>: Spawning Biomass value for year 2010 of 26771 mt, table 10 (<span class="citation" data-cites="stephens2014longspine">Stephens and Taylor (<a href="references.html#ref-stephens2014longspine" role="doc-biblioref">2013</a>)</span>). (Not used in DISPLACE, but included in the input files as a reference)</p></li>
</ul>
</section>
<section id="recruitment-1" class="level4" data-number="1.2.3.4">
<h4 data-number="1.2.3.4" class="anchored" data-anchor-id="recruitment-1"><span class="header-section-number">1.2.3.4</span> Recruitment</h4>
<p>Parameters needed to calculate <code>alpha</code> and <code>beta</code>:</p>
<ul>
<li><span class="math inline">\(h\)</span>: steepness is 0.75 from page 24 (<span class="citation" data-cites="fay2005longspine">Fay (<a href="references.html#ref-fay2005longspine" role="doc-biblioref">2005</a>)</span>) and 0.6 from table 6 (<span class="citation" data-cites="stephens2014longspine">Stephens and Taylor (<a href="references.html#ref-stephens2014longspine" role="doc-biblioref">2013</a>)</span>). We will use that from <span class="citation" data-cites="stephens2014longspine">Stephens and Taylor (<a href="references.html#ref-stephens2014longspine" role="doc-biblioref">2013</a>)</span>, also associated to <span class="math inline">\(R_0\)</span>.</li>
<li><span class="math inline">\(R_0\)</span>: this value is 136529 from table 8 (<span class="citation" data-cites="stephens2014longspine">Stephens and Taylor (<a href="references.html#ref-stephens2014longspine" role="doc-biblioref">2013</a>)</span>).</li>
<li><span class="math inline">\(SPR_0\)</span>: In table 8 we can find several SPR values, but none for the unfished equilibrium (<span class="citation" data-cites="stephens2014longspine">Stephens and Taylor (<a href="references.html#ref-stephens2014longspine" role="doc-biblioref">2013</a>)</span>). <span style="color:red; font-weight:bold;">MISSING</span></li>
</ul>
<ul>
<li><p><code>fixed recruitment</code>:</p>
<p>From Table c in <span class="citation" data-cites="stephens2014longspine">Stephens and Taylor (<a href="references.html#ref-stephens2014longspine" role="doc-biblioref">2013</a>)</span> (<a href="#tbl-longspine-recruitment">Table&nbsp;<span>1.9</span></a>), we get a mean recruitment value of 1.1568462^{5} thousand individuals.</p></li>
</ul>
<div class="cell" data-hash="populations_cache/html/tbl-longspine-recruitment_c25eb15ccbf35665cc34fa266eb29458">
<div class="cell-output-display">
<div id="tbl-longspine-recruitment" class="anchored">
<table class="table table-sm table-striped small">
<caption>Table&nbsp;1.9: Estimated recent trend in recruitment (1,000s) for Longspine Thornyhead.</caption>
<colgroup>
<col style="width: 17%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 5%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 6%">
<col style="width: 6%">
</colgroup>
<tbody>
<tr class="odd">
<td style="text-align: left;">year</td>
<td style="text-align: right;">2001</td>
<td style="text-align: right;">2002</td>
<td style="text-align: right;">2003</td>
<td style="text-align: right;">2004</td>
<td style="text-align: right;">2005</td>
<td style="text-align: right;">2006</td>
<td style="text-align: right;">2007</td>
<td style="text-align: right;">2008</td>
<td style="text-align: right;">2009</td>
<td style="text-align: right;">2010</td>
<td style="text-align: right;">2011</td>
<td style="text-align: right;">2012</td>
<td style="text-align: right;">2013</td>
</tr>
<tr class="even">
<td style="text-align: left;">recruitment_1000s</td>
<td style="text-align: right;">196400</td>
<td style="text-align: right;">110900</td>
<td style="text-align: right;">256300</td>
<td style="text-align: right;">93200</td>
<td style="text-align: right;">118000</td>
<td style="text-align: right;">101100</td>
<td style="text-align: right;">65200</td>
<td style="text-align: right;">72400</td>
<td style="text-align: right;">67200</td>
<td style="text-align: right;">68500</td>
<td style="text-align: right;">92700</td>
<td style="text-align: right;">132600</td>
<td style="text-align: right;">129400</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</section>
<section id="management-2" class="level4" data-number="1.2.3.5">
<h4 data-number="1.2.3.5" class="anchored" data-anchor-id="management-2"><span class="header-section-number">1.2.3.5</span> Management</h4>
<ul>
<li><p><code>FMSY</code>: Using the <code>Exploitation Rate Corresponding to SPR MSY</code> as proxy of <code>FMSY.</code> Values in table 8, and table e from <span class="citation" data-cites="stephens2014longspine">Stephens and Taylor (<a href="references.html#ref-stephens2014longspine" role="doc-biblioref">2013</a>)</span> and <span class="citation" data-cites="adams2019longspine">Adams, Hamel, and Taylor (<a href="references.html#ref-adams2019longspine" role="doc-biblioref">2019</a>)</span>, respectively. <code>FMSY</code>, <code>FMSYlower</code> and <code>FMSYupper</code> are 0.071, 0.068 and 0.0745, respectively (<code>FMSYupper</code> from average between both reports). (This value is also given to <code>F_target</code>).</p></li>
<li><p><code>B_trigger</code>: Currently, a trigger 40% for groundfish is used. We still need to define how DISPLACE uses such parameter. In the meantime we won’t include any management triggers (<code>B_trigger = 0</code>). <span style="color:orange; font-weight:bold;">TO DISCUSS</span></p></li>
<li><p><code>mls</code> and <code>mls_cat</code>: There is no minimum landing size for DTS. Thus, both values will be 0.</p></li>
<li><p><code>tac_tons</code>: based on table <a href="#tbl-allocation-data">Table&nbsp;<span>1.3</span></a>, For Longspine Thornyhead we get the following:</p></li>
</ul>
<div class="cell" data-hash="populations_cache/html/unnamed-chunk-56_1ac3153ec76778f89e4b676be21c0af2">
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<colgroup>
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">ACL_2017</th>
<th style="text-align: right;">ACL_2018</th>
<th style="text-align: right;">ACL_2019</th>
<th style="text-align: right;">ACL_2020</th>
<th style="text-align: right;">ACL_2021</th>
<th style="text-align: right;">ACL_2022</th>
<th style="text-align: right;">ACL_2023</th>
<th style="text-align: right;">ACL_2024</th>
<th style="text-align: right;">mean_ACL</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">3808</td>
<td style="text-align: right;">3614</td>
<td style="text-align: right;">3425</td>
<td style="text-align: right;">3250</td>
<td style="text-align: right;">3466</td>
<td style="text-align: right;">3226</td>
<td style="text-align: right;">3020</td>
<td style="text-align: right;">2845</td>
<td style="text-align: right;">3331.75</td>
</tr>
</tbody>
</table>
</div>
</div>
<ul>
<li><code>TAC_percent</code>: This variable represents the maximum allowed change (%) in TAC from one year to the next. Using the ACL values, we calculate an average year-to-year change of -3.984609%. Values within <code>Stock_biological_traits.csv</code> are expressed in per one. (This value is also applied to <code>F_percent</code>.)</li>
</ul>
<ul>
<li><code>fbar_assessment</code>: Using the exploitation rate from Table i (<span class="citation" data-cites="stephens2014longspine">Stephens and Taylor (<a href="references.html#ref-stephens2014longspine" role="doc-biblioref">2013</a>)</span>) as a proxy for fishing mortality (<a href="#tbl-longspine-fbar">Table&nbsp;<span>1.10</span></a>), we get a value of 0.0236364. <span style="color:orange; font-weight:bold;">TO DISCUSS</span></li>
</ul>
<div class="cell" data-hash="populations_cache/html/tbl-longspine-fbar_dcdc8a1847ee5b8721df26801104c993">
<div class="cell-output-display">
<div id="tbl-longspine-fbar" class="anchored">
<table class="table table-sm table-striped small">
<caption>Table&nbsp;1.10: Exploitation rates time series for Longspine Thornyhead, used as a proxy of fishing mortality.</caption>
<colgroup>
<col style="width: 15%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 6%">
</colgroup>
<tbody>
<tr class="odd">
<td style="text-align: left;">year</td>
<td style="text-align: right;">2003.000</td>
<td style="text-align: right;">2004.000</td>
<td style="text-align: right;">2005.000</td>
<td style="text-align: right;">2006.000</td>
<td style="text-align: right;">2007.000</td>
<td style="text-align: right;">2008.000</td>
<td style="text-align: right;">2009.000</td>
<td style="text-align: right;">2010.000</td>
<td style="text-align: right;">2011.000</td>
<td style="text-align: right;">2012.000</td>
<td style="text-align: right;">2013.00</td>
</tr>
<tr class="even">
<td style="text-align: left;">exploitation_rate</td>
<td style="text-align: right;">0.036</td>
<td style="text-align: right;">0.015</td>
<td style="text-align: right;">0.014</td>
<td style="text-align: right;">0.015</td>
<td style="text-align: right;">0.015</td>
<td style="text-align: right;">0.023</td>
<td style="text-align: right;">0.021</td>
<td style="text-align: right;">0.024</td>
<td style="text-align: right;">0.014</td>
<td style="text-align: right;">0.013</td>
<td style="text-align: right;">0.07</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<ul>
<li><code>fbar_age_min</code> and <code>fbar_age_max</code>: these refer to the minimum and maximum ages used to calculate the mean fishing mortality rate (<code>fbar_assessment</code>). These correspond to the youngest and oldest age classes included in the calculation. <span style="color:red; font-weight:bold;">MISSING</span></li>
</ul>
<div class="cell" data-hash="populations_cache/html/unnamed-chunk-61_80efb312b092e00930333be0968c7186">
<div class="cell-output-display">
<table class="table table-striped table-hover table-sm small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th" style="text-align: left; font-weight: bold;">Parameter</th>
<th data-quarto-table-cell-role="th" style="text-align: left; font-weight: bold;">Value</th>
<th data-quarto-table-cell-role="th" style="text-align: left; font-weight: bold;">Reference</th>
</tr>
</thead>
<tbody>
<tr class="odd" data-grouplength="5">
<td colspan="3" style="border-bottom: 1px solid"><strong>Somatic growth</strong></td>
</tr>
<tr class="even">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">Linf</td>
<td style="text-align: left;">2.818212e+01</td>
<td style="text-align: left;">@fay2005longspine</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">CV_Linf</td>
<td style="text-align: left;">4.000000e-02</td>
<td style="text-align: left;">@fay2005longspine</td>
</tr>
<tr class="even">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">K</td>
<td style="text-align: left;">1.085050e-01</td>
<td style="text-align: left;">@fay2005longspine</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">t0</td>
<td style="text-align: left;">-2.020000e+00</td>
<td style="text-align: left;">@fay2005longspine</td>
</tr>
<tr class="even">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">CV_recru</td>
<td style="text-align: left;">6.582776e-01</td>
<td style="text-align: left;">@fay2005longspine</td>
</tr>
<tr class="odd" data-grouplength="2">
<td colspan="3" style="border-bottom: 1px solid"><strong>Length-weight relationship</strong></td>
</tr>
<tr class="even">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">a</td>
<td style="text-align: left;">4.300000e-06</td>
<td style="text-align: left;">@fay2005longspine, @stephens2014longspine</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">b</td>
<td style="text-align: left;">3.352000e+00</td>
<td style="text-align: left;">@fay2005longspine, @stephens2014longspine</td>
</tr>
<tr class="even" data-grouplength="3">
<td colspan="3" style="border-bottom: 1px solid"><strong>Maturity</strong></td>
</tr>
<tr class="odd">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">L50</td>
<td style="text-align: left;">1.782600e+01</td>
<td style="text-align: left;">@fay2005longspine, @stephens2014longspine</td>
</tr>
<tr class="even">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">mat_cat</td>
<td style="text-align: left;">3.000000e+00</td>
<td style="text-align: left;">@fay2005longspine, @stephens2014longspine</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">r_age</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">@fay2005longspine</td>
</tr>
<tr class="even" data-grouplength="6">
<td colspan="3" style="border-bottom: 1px solid"><strong>Recruitment</strong></td>
</tr>
<tr class="odd">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">ssb_assessment</td>
<td style="text-align: left;">2.677100e+04</td>
<td style="text-align: left;">@stephens2014longspine</td>
</tr>
<tr class="even">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">h</td>
<td style="text-align: left;">6.000000e-01</td>
<td style="text-align: left;">@stephens2014longspine</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">R0</td>
<td style="text-align: left;">1.365290e+05</td>
<td style="text-align: left;">@stephens2014longspine</td>
</tr>
<tr class="even">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">SPR_0</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">alpha</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">beta</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="odd" data-grouplength="11">
<td colspan="3" style="border-bottom: 1px solid"><strong>Management</strong></td>
</tr>
<tr class="even">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">FMSY</td>
<td style="text-align: left;">7.100000e-02</td>
<td style="text-align: left;">@wetzel2021doversole_benchmark</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">FMSYlower</td>
<td style="text-align: left;">6.800000e-02</td>
<td style="text-align: left;">@wetzel2021doversole_benchmark</td>
</tr>
<tr class="even">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">FMSYupper</td>
<td style="text-align: left;">7.450000e-02</td>
<td style="text-align: left;">@wetzel2021doversole_benchmark</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">B_trigger</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">mls</td>
<td style="text-align: left;">0.000000e+00</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">mls_cat</td>
<td style="text-align: left;">0.000000e+00</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">tac_tons</td>
<td style="text-align: left;">3.331750e+03</td>
<td style="text-align: left;">@PFMC2022</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">TAC_percent</td>
<td style="text-align: left;">-3.984610e-02</td>
<td style="text-align: left;">@PFMC2022</td>
</tr>
<tr class="even">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">fbar_assessment</td>
<td style="text-align: left;">2.363640e-02</td>
<td style="text-align: left;">@stephens2014longspine</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">fbar_age_min</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">fbar_age_max</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
</tr>
</tbody>
</table>


</div>
</div>
</section>
</section>
<section id="shortpine-thornyhead" class="level3" data-number="1.2.4">
<h3 data-number="1.2.4" class="anchored" data-anchor-id="shortpine-thornyhead"><span class="header-section-number">1.2.4</span> Shortpine Thornyhead</h3>
<p>(<em>Sebastolobus alascanus</em>) (FAO code SJU)</p>
<hr>
<section id="somatic-growth-3" class="level4" data-number="1.2.4.1">
<h4 data-number="1.2.4.1" class="anchored" data-anchor-id="somatic-growth-3"><span class="header-section-number">1.2.4.1</span> Somatic growth</h4>
<ul>
<li><code>Linf</code>: <span class="citation" data-cites="zahner2023shortspine">J. A. Zahner et al. (<a href="references.html#ref-zahner2023shortspine" role="doc-biblioref">2023</a>)</span> assessment contains both von Bertalanffy and Schnute parameters, defining <code>Linf</code> as 111 for females and 79.4 for males (mean value of 95.2).</li>
</ul>
<div class="cell" data-hash="populations_cache/html/tbl-shortspine-Schnute_18845b30dbc67e54ce8756fe16da6466">
<div class="cell-output-display">
<div id="tbl-shortspine-Schnute" class="anchored">
<table class="table table-sm table-striped small">
<caption>Table&nbsp;1.11: Schnute and von Bertalanffy growth parameters for Longspine Thornyhead.</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Parameter</th>
<th style="text-align: right;">Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Females La1</td>
<td style="text-align: right;">11.4000</td>
</tr>
<tr class="even">
<td style="text-align: left;">Females La2</td>
<td style="text-align: right;">73.6000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Females K</td>
<td style="text-align: right;">0.0099</td>
</tr>
<tr class="even">
<td style="text-align: left;">Males La1</td>
<td style="text-align: right;">9.2000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Males La2</td>
<td style="text-align: right;">66.1000</td>
</tr>
<tr class="even">
<td style="text-align: left;">Males K</td>
<td style="text-align: right;">0.0168</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Age1</td>
<td style="text-align: right;">1.0000</td>
</tr>
<tr class="even">
<td style="text-align: left;">Age2</td>
<td style="text-align: right;">100.0000</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>This stock assessment gives us the opportunity to double-check whether the von Bertalanffy parameters derived from the Schnute ones, done so far, are correct. Using the parameters summarized in <a href="#tbl-shortspine-Schnute">Table&nbsp;<span>1.11</span></a>, as detailed on page 16 of <span class="citation" data-cites="zahner2023shortspine">J. A. Zahner et al. (<a href="references.html#ref-zahner2023shortspine" role="doc-biblioref">2023</a>)</span>, we get a <code>Linf</code> of 111 for females and 79.4 for males, corresponding to the values reported in the assessment.</p>
<ul>
<li><p><code>CV_Linf</code>: The only values available are <code>CV_old_Fem_GP_1</code> and <code>CV_old_Mal_GP_1</code> 0.1090340 in table 20 (<span class="citation" data-cites="zahner2023shortspine">J. A. Zahner et al. (<a href="references.html#ref-zahner2023shortspine" role="doc-biblioref">2023</a>)</span>).</p></li>
<li><p><code>K</code>: 0.0099 for females and 0.0168 for males from page 16 (<span class="citation" data-cites="zahner2023shortspine">J. A. Zahner et al. (<a href="references.html#ref-zahner2023shortspine" role="doc-biblioref">2023</a>)</span>). Values also available in table 20, <code>VonBert_K_Fem_GP_1</code> 0.0098986 and <code>VonBert_K_Mal_GP_1</code> 0.0167854. We will use the mean value from those non rounded values in table 20 (0.013342).</p></li>
<li><p><code>t0</code>: -8.931 for females and -5.314 for males from page 16 (<span class="citation" data-cites="zahner2023shortspine">J. A. Zahner et al. (<a href="references.html#ref-zahner2023shortspine" role="doc-biblioref">2023</a>)</span>). Mean value to be used -7.1225.</p></li>
</ul>
<p>Same as done with <code>Linf</code>, considering that the stock assessment expresses growth using Schnute parameters, we can check the <code>t0</code> derivation from Schnute parameters. However, unlike <code>Linf</code>, we are not getting the same results (-6.3297409). <span style="color:orange; font-weight:bold;">TO DISCUSS</span></p>
<ul>
<li><code>CV_recru</code>: from page 21 (<span class="citation" data-cites="zahner2023shortspine">J. A. Zahner et al. (<a href="references.html#ref-zahner2023shortspine" role="doc-biblioref">2023</a>)</span>) <span class="math inline">\(\sigma R = 0.5\)</span>. Thus CV would be 0.5329404.</li>
</ul>
</section>
<section id="length-weight-relationship-3" class="level4" data-number="1.2.4.2">
<h4 data-number="1.2.4.2" class="anchored" data-anchor-id="length-weight-relationship-3"><span class="header-section-number">1.2.4.2</span> Length-weight relationship</h4>
<ul>
<li><p><code>a</code>: 4.86e-6 for females and 4.69e-6 for males from page 15 (<span class="citation" data-cites="zahner2023shortspine">J. A. Zahner et al. (<a href="references.html#ref-zahner2023shortspine" role="doc-biblioref">2023</a>)</span>). Mean value used 4.775^{-6}.</p></li>
<li><p><code>b</code>: 3.26 for females and 3.25 for males from page 15 (<span class="citation" data-cites="zahner2023shortspine">J. A. Zahner et al. (<a href="references.html#ref-zahner2023shortspine" role="doc-biblioref">2023</a>)</span>). Mean value used 3.255.</p></li>
</ul>
</section>
<section id="maturity-3" class="level4" data-number="1.2.4.3">
<h4 data-number="1.2.4.3" class="anchored" data-anchor-id="maturity-3"><span class="header-section-number">1.2.4.3</span> Maturity</h4>
<ul>
<li><p><code>L50</code>: 31.4 cm from page 26. Also available in table 20 under <code>Mat50%_Fem_GP_1</code> 31.4247000 (<span class="citation" data-cites="zahner2023shortspine">J. A. Zahner et al. (<a href="references.html#ref-zahner2023shortspine" role="doc-biblioref">2023</a>)</span>).</p></li>
<li><p><code>mat_cat</code>: This corresponds to the maturity size DISPLACE category at the L50. For an <code>L50</code> of 31.4 cm is 5.</p></li>
<li><p><code>r_age</code>: No reference is available, but this is not an issue since it is not used in DISPLACE and is included solely for reference purposes. Set value to <code>NA</code> to prevent any errors.</p></li>
<li><p><code>ssb_assessment</code>: Spawning Output value for year 2010 of 10135 mt, table 11 (<span class="citation" data-cites="zahner2023shortspine">J. A. Zahner et al. (<a href="references.html#ref-zahner2023shortspine" role="doc-biblioref">2023</a>)</span>). (Not used in DISPLACE, but included in the input files as a reference)</p></li>
</ul>
</section>
<section id="recruitment-2" class="level4" data-number="1.2.4.4">
<h4 data-number="1.2.4.4" class="anchored" data-anchor-id="recruitment-2"><span class="header-section-number">1.2.4.4</span> Recruitment</h4>
<p>Parameters needed to calculate <code>alpha</code> and <code>beta</code>:</p>
<ul>
<li><span class="math inline">\(h\)</span>: steepness is 0.72 from page iii and in table 20 under SR_BH_steep (<span class="citation" data-cites="zahner2023shortspine">J. A. Zahner et al. (<a href="references.html#ref-zahner2023shortspine" role="doc-biblioref">2023</a>)</span>).</li>
<li><span class="math inline">\(R_0\)</span>: 12580 from table v (<span class="citation" data-cites="zahner2023shortspine">J. A. Zahner et al. (<a href="references.html#ref-zahner2023shortspine" role="doc-biblioref">2023</a>)</span>).</li>
<li><span class="math inline">\(SPR_0\)</span>: In table v we can find several SPR values, but none for the unfished equilibrium (<span class="citation" data-cites="zahner2023shortspine">J. A. Zahner et al. (<a href="references.html#ref-zahner2023shortspine" role="doc-biblioref">2023</a>)</span>). <span style="color:red; font-weight:bold;">MISSING</span></li>
</ul>
<!-- ###### SPR_0 -->
<!-- We can calculate $SPR_0$ from the age specofic egg production. Egg production at each age $a$ is given by $E_a = l_a \cdot m_a \cdot f_a$ where $l_a$ is the survivorship at age $a$ -->
<ul>
<li><p><code>fixed recruitment</code>:</p>
<p>From Table iii in <span class="citation" data-cites="zahner2023shortspine">J. A. Zahner et al. (<a href="references.html#ref-zahner2023shortspine" role="doc-biblioref">2023</a>)</span> (<a href="#tbl-shortspine-recruitment">Table&nbsp;<span>1.12</span></a>), we get a mean recruitment value of 1.0325545^{4} thousand individuals.</p></li>
</ul>
<div class="cell" data-hash="populations_cache/html/tbl-shortspine-recruitment_ddaa067e001223f1a5c1a447b49d9e8f">
<div class="cell-output-display">
<div id="tbl-shortspine-recruitment" class="anchored">
<table class="table table-sm table-striped small">
<caption>Table&nbsp;1.12: Estimated recent trend in recruitment (1,000s) for Shortspine Thornyhead.</caption>
<colgroup>
<col style="width: 22%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 7%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
</colgroup>
<tbody>
<tr class="odd">
<td style="text-align: left;">year</td>
<td style="text-align: right;">2013</td>
<td style="text-align: right;">2014</td>
<td style="text-align: right;">2015</td>
<td style="text-align: right;">2016</td>
<td style="text-align: right;">2017</td>
<td style="text-align: right;">2018</td>
<td style="text-align: right;">2019</td>
<td style="text-align: right;">2020</td>
<td style="text-align: right;">2021</td>
<td style="text-align: right;">2022</td>
<td style="text-align: right;">2023</td>
</tr>
<tr class="even">
<td style="text-align: left;">recruitment_1000s</td>
<td style="text-align: right;">9622</td>
<td style="text-align: right;">9650</td>
<td style="text-align: right;">9783</td>
<td style="text-align: right;">10155</td>
<td style="text-align: right;">9995</td>
<td style="text-align: right;">9990</td>
<td style="text-align: right;">10354</td>
<td style="text-align: right;">10839</td>
<td style="text-align: right;">11299</td>
<td style="text-align: right;">10952</td>
<td style="text-align: right;">10942</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</section>
<section id="management-3" class="level4" data-number="1.2.4.5">
<h4 data-number="1.2.4.5" class="anchored" data-anchor-id="management-3"><span class="header-section-number">1.2.4.5</span> Management</h4>
<ul>
<li><p><code>FMSY</code>: Using the <code>Exploitation Rate Corresponding to SPR MSY</code> as proxy of <code>FMSY</code>. Values from table v (<span class="citation" data-cites="zahner2023shortspine">J. A. Zahner et al. (<a href="references.html#ref-zahner2023shortspine" role="doc-biblioref">2023</a>)</span>). <code>FMSY</code>, <code>FMSYlower</code> and <code>FMSYupper</code> are 0.017, 0.016 and 0.017, respectively. (This value is also given to <code>F_target</code>).</p></li>
<li><p><code>B_trigger</code>: Currently, a trigger 40% for groundfish is used. We still need to define how DISPLACE uses such parameter. In the meantime we won’t include any management triggers (<code>B_trigger = 0</code>). <span style="color:orange; font-weight:bold;">TO DISCUSS</span></p></li>
<li><p><code>mls</code> and <code>mls_cat</code>: There is no minimum landing size for DTS. Thus, both values will be 0.</p></li>
<li><p><code>tac_tons</code>: based on table <a href="#tbl-allocation-data">Table&nbsp;<span>1.3</span></a>, For Shortspine Thornyhead we get the following:</p></li>
</ul>
<div class="cell" data-hash="populations_cache/html/unnamed-chunk-76_3205d8c29215f00471c9aafe17c7dd07">
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<colgroup>
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">ACL_2017</th>
<th style="text-align: right;">ACL_2018</th>
<th style="text-align: right;">ACL_2019</th>
<th style="text-align: right;">ACL_2020</th>
<th style="text-align: right;">ACL_2021</th>
<th style="text-align: right;">ACL_2022</th>
<th style="text-align: right;">ACL_2023</th>
<th style="text-align: right;">ACL_2024</th>
<th style="text-align: right;">mean_ACL</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">2619</td>
<td style="text-align: right;">2596</td>
<td style="text-align: right;">2573</td>
<td style="text-align: right;">2552</td>
<td style="text-align: right;">2184</td>
<td style="text-align: right;">2130</td>
<td style="text-align: right;">2078</td>
<td style="text-align: right;">2030</td>
<td style="text-align: right;">2345.25</td>
</tr>
</tbody>
</table>
</div>
</div>
<ul>
<li><code>TAC_percent</code>: This variable represents the maximum allowed change (%) in TAC from one year to the next. Using the ACL values, we calculate an average year-to-year change of -3.4605946%. Values within <code>Stock_biological_traits.csv</code> are expressed in per one. (This value is also applied to <code>F_percent</code>.)</li>
</ul>
<ul>
<li><code>fbar_assessment</code>: Using the exploitation rate from Table iv (<span class="citation" data-cites="zahner2023shortspine">J. A. Zahner et al. (<a href="references.html#ref-zahner2023shortspine" role="doc-biblioref">2023</a>)</span>) as a proxy for fishing mortality (<a href="#tbl-shortspine-fbar">Table&nbsp;<span>1.13</span></a>), we get a value of 0.00913. <span style="color:orange; font-weight:bold;">TO DISCUSS</span></li>
</ul>
<div class="cell" data-hash="populations_cache/html/tbl-shortspine-fbar_3dad0227052322d74ca2103cc5028fa5">
<div class="cell-output-display">
<div id="tbl-shortspine-fbar" class="anchored">
<table class="table table-sm table-striped small">
<caption>Table&nbsp;1.13: Exploitation rates time series for Shortspine Thornyhead, used as a proxy of fishing mortality.</caption>
<colgroup>
<col style="width: 16%">
<col style="width: 8%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
</colgroup>
<tbody>
<tr class="odd">
<td style="text-align: left;">year</td>
<td style="text-align: right;">2013.000</td>
<td style="text-align: right;">2014.00</td>
<td style="text-align: right;">2015.00</td>
<td style="text-align: right;">2016.0000</td>
<td style="text-align: right;">2017.0000</td>
<td style="text-align: right;">2018.0000</td>
<td style="text-align: right;">2019.0000</td>
<td style="text-align: right;">2.02e+03</td>
<td style="text-align: right;">2021.0000</td>
<td style="text-align: right;">2022.0000</td>
</tr>
<tr class="even">
<td style="text-align: left;">exploitation_rate</td>
<td style="text-align: right;">0.012</td>
<td style="text-align: right;">0.01</td>
<td style="text-align: right;">0.01</td>
<td style="text-align: right;">0.0107</td>
<td style="text-align: right;">0.0118</td>
<td style="text-align: right;">0.0103</td>
<td style="text-align: right;">0.0085</td>
<td style="text-align: right;">5.10e-03</td>
<td style="text-align: right;">0.0053</td>
<td style="text-align: right;">0.0076</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<ul>
<li><code>fbar_age_min</code> and <code>fbar_age_max</code>: these refer to the minimum and maximum ages used to calculate the mean fishing mortality rate (<code>fbar_assessment</code>). These correspond to the youngest and oldest age classes included in the calculation. <span style="color:red; font-weight:bold;">MISSING</span></li>
</ul>
<div class="cell" data-hash="populations_cache/html/unnamed-chunk-81_c4b9537ce8531f91269c3e5e8a17fd28">
<div class="cell-output-display">
<table class="table table-striped table-hover table-sm small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th" style="text-align: left; font-weight: bold;">Parameter</th>
<th data-quarto-table-cell-role="th" style="text-align: left; font-weight: bold;">Value</th>
<th data-quarto-table-cell-role="th" style="text-align: left; font-weight: bold;">Reference</th>
</tr>
</thead>
<tbody>
<tr class="odd" data-grouplength="5">
<td colspan="3" style="border-bottom: 1px solid"><strong>Somatic growth</strong></td>
</tr>
<tr class="even">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">Linf</td>
<td style="text-align: left;">95.2000000</td>
<td style="text-align: left;">@zahner2023shortspine</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">CV_Linf</td>
<td style="text-align: left;">0.1090340</td>
<td style="text-align: left;">@zahner2023shortspine</td>
</tr>
<tr class="even">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">K</td>
<td style="text-align: left;">0.0133420</td>
<td style="text-align: left;">@zahner2023shortspine</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">t0</td>
<td style="text-align: left;">-7.1225000</td>
<td style="text-align: left;">@zahner2023shortspine</td>
</tr>
<tr class="even">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">CV_recru</td>
<td style="text-align: left;">0.5329404</td>
<td style="text-align: left;">@zahner2023shortspine</td>
</tr>
<tr class="odd" data-grouplength="2">
<td colspan="3" style="border-bottom: 1px solid"><strong>Length-weight relationship</strong></td>
</tr>
<tr class="even">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">a</td>
<td style="text-align: left;">0.0000048</td>
<td style="text-align: left;">@wetzel2021doversole_benchmark</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">b</td>
<td style="text-align: left;">3.2550000</td>
<td style="text-align: left;">@wetzel2021doversole_benchmark</td>
</tr>
<tr class="even" data-grouplength="3">
<td colspan="3" style="border-bottom: 1px solid"><strong>Maturity</strong></td>
</tr>
<tr class="odd">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">L50</td>
<td style="text-align: left;">31.4000000</td>
<td style="text-align: left;">@zahner2023shortspine</td>
</tr>
<tr class="even">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">mat_cat</td>
<td style="text-align: left;">5.0000000</td>
<td style="text-align: left;">@zahner2023shortspine</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">r_age</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="even" data-grouplength="6">
<td colspan="3" style="border-bottom: 1px solid"><strong>Recruitment</strong></td>
</tr>
<tr class="odd">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">ssb_assessment</td>
<td style="text-align: left;">10135.0000000</td>
<td style="text-align: left;">@zahner2023shortspine</td>
</tr>
<tr class="even">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">h</td>
<td style="text-align: left;">0.7200000</td>
<td style="text-align: left;">@zahner2023shortspine</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">R0</td>
<td style="text-align: left;">12580.0000000</td>
<td style="text-align: left;">@zahner2023shortspine</td>
</tr>
<tr class="even">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">SPR_0</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">alpha</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">beta</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="odd" data-grouplength="11">
<td colspan="3" style="border-bottom: 1px solid"><strong>Management</strong></td>
</tr>
<tr class="even">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">FMSY</td>
<td style="text-align: left;">0.0170000</td>
<td style="text-align: left;">@zahner2023shortspine</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">FMSYlower</td>
<td style="text-align: left;">0.0160000</td>
<td style="text-align: left;">@zahner2023shortspine</td>
</tr>
<tr class="even">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">FMSYupper</td>
<td style="text-align: left;">0.0170000</td>
<td style="text-align: left;">@zahner2023shortspine</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">B_trigger</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">mls</td>
<td style="text-align: left;">0.0000000</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">mls_cat</td>
<td style="text-align: left;">0.0000000</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">tac_tons</td>
<td style="text-align: left;">2345.2500000</td>
<td style="text-align: left;">@PFMC2022</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">TAC_percent</td>
<td style="text-align: left;">-0.0346059</td>
<td style="text-align: left;">@PFMC2022</td>
</tr>
<tr class="even">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">fbar_assessment</td>
<td style="text-align: left;">0.0091300</td>
<td style="text-align: left;">@zahner2023shortspine</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">fbar_age_min</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">fbar_age_max</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
</tr>
</tbody>
</table>


</div>
</div>
</section>
</section>
<section id="sizespectra-option-parameters" class="level3" data-number="1.2.5">
<h3 data-number="1.2.5" class="anchored" data-anchor-id="sizespectra-option-parameters"><span class="header-section-number">1.2.5</span> SizeSpectra option parameters</h3>
<p>The following parameters can be ignored by setting them to 0 if we are not considering trophic interactions (<span class="citation" data-cites="blanchard2017sizespectra">Blanchard et al. (<a href="references.html#ref-blanchard2017sizespectra" role="doc-biblioref">2017</a>)</span>): <code>Winf</code>, <code>k</code>, <code>etha_m</code>, <code>kappa</code>, <code>q</code>, <code>n</code> and <code>fzeroest</code>.</p>
<p>These parameters are only relevant if the <code>sizeSpectra</code> option is activated. Please refer to the activation of options in the scenarios <code>.dat</code> files.</p>
</section>
</section>
<section id="species-distribution" class="level2" data-number="1.3">
<h2 data-number="1.3" class="anchored" data-anchor-id="species-distribution"><span class="header-section-number">1.3</span> Species distribution</h2>
<p>In this section, we will generate the population distribution needed in <code>POPULATIONS/SpatialLayers</code> to run DISPLACE. DISPLACE can ingest biomass density on any unit and at a continuous scale. Therefore, using species distribution data from <span class="citation" data-cites="liu2023species">Liu et al. (<a href="references.html#ref-liu2023species" role="doc-biblioref">2023</a>)</span>, we’ll spatially join it to a grid of interest and export it to a shapefile with the input formatting as detailed in <a href="#tbl-sp-dis-file">Table&nbsp;<span>1.14</span></a>, with <code>GRIDCODE</code> containing the biomass density values.</p>
<div class="cell" data-hash="populations_cache/html/tbl-sp-dis-file_3a19c2f6ae8e1a53d5484a13cff1c3da">
<div class="cell-output-display">
<div id="tbl-sp-dis-file" class="anchored">
<table class="table table-sm table-striped small">
<caption>Table&nbsp;1.14: Sample of the structure of the shapefile containing the species distributioin values</caption>
<thead>
<tr class="header">
<th style="text-align: right;">idx</th>
<th style="text-align: left;">fao_code</th>
<th style="text-align: right;">GRIDCODE</th>
<th style="text-align: left;">x</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">0</td>
<td style="text-align: left;">SAB</td>
<td style="text-align: right;">424.3856</td>
<td style="text-align: left;">POLYGON ((-119.35 32.05, -1…</td>
</tr>
<tr class="even">
<td style="text-align: right;">0</td>
<td style="text-align: left;">SAB</td>
<td style="text-align: right;">386.2080</td>
<td style="text-align: left;">POLYGON ((-119.25 32.05, -1…</td>
</tr>
<tr class="odd">
<td style="text-align: right;">0</td>
<td style="text-align: left;">SAB</td>
<td style="text-align: right;">353.0033</td>
<td style="text-align: left;">POLYGON ((-119.15 32.05, -1…</td>
</tr>
<tr class="even">
<td style="text-align: right;">0</td>
<td style="text-align: left;">SAB</td>
<td style="text-align: right;">317.0813</td>
<td style="text-align: left;">POLYGON ((-119.05 32.05, -1…</td>
</tr>
<tr class="odd">
<td style="text-align: right;">0</td>
<td style="text-align: left;">SAB</td>
<td style="text-align: right;">302.6207</td>
<td style="text-align: left;">POLYGON ((-118.95 32.05, -1…</td>
</tr>
<tr class="even">
<td style="text-align: right;">0</td>
<td style="text-align: left;">SAB</td>
<td style="text-align: right;">335.1042</td>
<td style="text-align: left;">POLYGON ((-118.85 32.05, -1…</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<div class="cell" data-hash="populations_cache/html/fig-sp-distribution_aa856b716b0cfd5476452b300794cc81">
<div class="cell-output-display">
<div id="fig-sp-distribution" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="populations_files/figure-html/fig-sp-distribution-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Figure&nbsp;1.1: Species distribution in a continous scale from mean biomass values (kg/km2).</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="abundances-szgroup" class="level2" data-number="1.4">
<h2 data-number="1.4" class="anchored" data-anchor-id="abundances-szgroup"><span class="header-section-number">1.4</span> Stock abundances at szgroup</h2>
<p>The units in the <code>Stock_abundances_at_szgroup.csv</code> file represent the number of individuals. DISPLACE is designed to process a specific number of length bins (<code>0:13</code>). Therefore, we need to adapt them based on the largest size bin for which we have abundance information (i.e., 80 cm for sablefish). The length bins will then be 6 cm.</p>
<p>To get these abundance values, we’ll use the catch distribution from the scientific surveys done for the stock assessments. These surveys give us the proportion of the total abundance by size group. We’ll then apply this to the yearly biomass values from the stock assessment’s modeled total biomass. After that, we’ll transform the biomass values into the number of fish using the length-weight relationship for each species. It’s worth noting that some stock assessments have a typo and weight data is in kilograms instead of grams.</p>
<p>The code to generate such a file is available under <code>functions_pop.R</code> and produces the table shown below.</p>
<div class="cell" data-hash="populations_cache/html/fig-abundances-szgroup_363c286442a4cdf42f6842b2e737fc6e">
<div id="fig-abundances-szgroup" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<table class="table table-sm table-striped small">
<colgroup>
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 7%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">stock</th>
<th style="text-align: right;">0</th>
<th style="text-align: right;">1</th>
<th style="text-align: right;">2</th>
<th style="text-align: right;">3</th>
<th style="text-align: right;">4</th>
<th style="text-align: right;">5</th>
<th style="text-align: right;">6</th>
<th style="text-align: right;">7</th>
<th style="text-align: right;">8</th>
<th style="text-align: right;">9</th>
<th style="text-align: right;">10</th>
<th style="text-align: right;">11</th>
<th style="text-align: right;">12</th>
<th style="text-align: right;">13</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">SAB</td>
<td style="text-align: right;">16321</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">117071.1</td>
<td style="text-align: right;">900204.7</td>
<td style="text-align: right;">2957731.7</td>
<td style="text-align: right;">64443823</td>
<td style="text-align: right;">161069586</td>
<td style="text-align: right;">40030449</td>
<td style="text-align: right;">20453968.1</td>
<td style="text-align: right;">3586942.8</td>
<td style="text-align: right;">168015.2</td>
<td style="text-align: right;">35788.41</td>
<td style="text-align: right;">1226.409</td>
</tr>
<tr class="even">
<td style="text-align: left;">MIP</td>
<td style="text-align: right;">256930</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">46063450</td>
<td style="text-align: right;">125580385.4</td>
<td style="text-align: right;">67514127.9</td>
<td style="text-align: right;">148861830.9</td>
<td style="text-align: right;">342919698</td>
<td style="text-align: right;">170174509</td>
<td style="text-align: right;">33443062</td>
<td style="text-align: right;">925009.7</td>
<td style="text-align: right;">0.0</td>
<td style="text-align: right;">0.0</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">SJZ</td>
<td style="text-align: right;">68454</td>
<td style="text-align: right;">340982410</td>
<td style="text-align: right;">378117403</td>
<td style="text-align: right;">326556783.7</td>
<td style="text-align: right;">68729771.9</td>
<td style="text-align: right;">259346.3</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0.0</td>
<td style="text-align: right;">0.0</td>
<td style="text-align: right;">0.0</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.000</td>
</tr>
<tr class="even">
<td style="text-align: left;">SJU</td>
<td style="text-align: right;">13805</td>
<td style="text-align: right;">59005701</td>
<td style="text-align: right;">89485777</td>
<td style="text-align: right;">151768972.3</td>
<td style="text-align: right;">143613451.5</td>
<td style="text-align: right;">63939390.8</td>
<td style="text-align: right;">15344761</td>
<td style="text-align: right;">5834082</td>
<td style="text-align: right;">2397778</td>
<td style="text-align: right;">1447801.7</td>
<td style="text-align: right;">851419.2</td>
<td style="text-align: right;">210580.6</td>
<td style="text-align: right;">32859.72</td>
<td style="text-align: right;">0.000</td>
</tr>
</tbody>
</table>
<figcaption class="figure-caption">Figure&nbsp;1.2: Stock_abundances_at_szgroup.csv inout file contents.</figcaption>
</figure>
</div>
</div>
<section id="stock-abundances-at-age" class="level3" data-number="1.4.1">
<h3 data-number="1.4.1" class="anchored" data-anchor-id="stock-abundances-at-age"><span class="header-section-number">1.4.1</span> Stock abundances at age</h3>
<p>The units in the <code>Stock_abundance_at_age.csv</code> file are the number of individuals. DISPLACE is designed to process a specific number of age bins which is <strong>13</strong> (<code>0:12</code>), so we will have to adapt them based on our population max ages.</p>
<div class="cell" data-hash="populations_cache/html/fig-max-age_6b3ff478ff2e72c36f9f1ed37a6dddcd">
<div id="fig-max-age" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<table class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Common.Name</th>
<th style="text-align: right;">Maximum.Age</th>
<th style="text-align: left;">Bib.References</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Sablefish</td>
<td style="text-align: right;">102</td>
<td style="text-align: left;"><span class="citation" data-cites="head2014maturity">M. Head, Keller, and Bradburn (<a href="references.html#ref-head2014maturity" role="doc-biblioref">2014</a>)</span></td>
</tr>
<tr class="even">
<td style="text-align: left;">Shortspine Thornyhead</td>
<td style="text-align: right;">100</td>
<td style="text-align: left;"><span class="citation" data-cites="zahner2023status">J. Zahner et al. (<a href="references.html#ref-zahner2023status" role="doc-biblioref">2023</a>)</span></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Longspine Thornyhead</td>
<td style="text-align: right;">45</td>
<td style="text-align: left;"><span class="citation" data-cites="pearson2003reproductive">Pearson and Gunderson (<a href="references.html#ref-pearson2003reproductive" role="doc-biblioref">2003</a>)</span></td>
</tr>
<tr class="even">
<td style="text-align: left;">Dover Sole</td>
<td style="text-align: right;">58</td>
<td style="text-align: left;"><span class="citation" data-cites="jacobson1993bathymetric">Jacobson and Hunter (<a href="references.html#ref-jacobson1993bathymetric" role="doc-biblioref">1993</a>)</span></td>
</tr>
</tbody>
</table>
<figcaption class="figure-caption">Figure&nbsp;1.3: Detail of maximum ages.</figcaption>
</figure>
</div>
</div>
<p>Given a max age of 102, the bins will be 8 years. However, DISPLACE uses this to transform age into size groups. Since we already have abundance information by size from <code>Stock_abundances_at_szgroup.csv</code>, this table is not required. Thus, we will generate an empty table with 0s.</p>
</section>
</section>
<section id="stock-prices-data" class="level2" data-number="1.5">
<h2 data-number="1.5" class="anchored" data-anchor-id="stock-prices-data"><span class="header-section-number">1.5</span> Stock prices data</h2>
<p>The file <code>Stock_prices_data.csv</code> contains prices per kg for three length categories: <code>small</code>, <code>medium</code>, and <code>large</code>, for any desired currency unit. These categories can be freely defined based on the length bins. For this study case, we have defined them as follows:</p>
<div class="cell" data-hash="populations_cache/html/fig-size-groups_2749ed791b63570480247fec0ffffce0">
<div id="fig-size-groups" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<table class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Species</th>
<th style="text-align: left;">Size</th>
<th style="text-align: left;">sz_group</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">SAB</td>
<td style="text-align: left;">small</td>
<td style="text-align: left;">0, 1, 2, 3, 4, 5</td>
</tr>
<tr class="even">
<td style="text-align: left;">SAB</td>
<td style="text-align: left;">medium</td>
<td style="text-align: left;">6, 7, 8, 9</td>
</tr>
<tr class="odd">
<td style="text-align: left;">SAB</td>
<td style="text-align: left;">large</td>
<td style="text-align: left;">10, 11, 12, 13</td>
</tr>
<tr class="even">
<td style="text-align: left;">SJU</td>
<td style="text-align: left;">small</td>
<td style="text-align: left;">0, 1, 2, 3, 4, 5</td>
</tr>
<tr class="odd">
<td style="text-align: left;">SJU</td>
<td style="text-align: left;">medium</td>
<td style="text-align: left;">6, 7, 8, 9</td>
</tr>
<tr class="even">
<td style="text-align: left;">SJU</td>
<td style="text-align: left;">large</td>
<td style="text-align: left;">10, 11, 12, 13</td>
</tr>
<tr class="odd">
<td style="text-align: left;">SJZ</td>
<td style="text-align: left;">small</td>
<td style="text-align: left;">0, 1, 2, 3, 4, 5</td>
</tr>
<tr class="even">
<td style="text-align: left;">SJZ</td>
<td style="text-align: left;">medium</td>
<td style="text-align: left;">6, 7, 8, 9</td>
</tr>
<tr class="odd">
<td style="text-align: left;">SJZ</td>
<td style="text-align: left;">large</td>
<td style="text-align: left;">10, 11, 12, 13</td>
</tr>
<tr class="even">
<td style="text-align: left;">MIP</td>
<td style="text-align: left;">small</td>
<td style="text-align: left;">0, 1, 2, 3, 4, 5</td>
</tr>
<tr class="odd">
<td style="text-align: left;">MIP</td>
<td style="text-align: left;">medium</td>
<td style="text-align: left;">6, 7, 8, 9</td>
</tr>
<tr class="even">
<td style="text-align: left;">MIP</td>
<td style="text-align: left;">large</td>
<td style="text-align: left;">10, 11, 12, 13</td>
</tr>
</tbody>
</table>
<figcaption class="figure-caption">Figure&nbsp;1.4: Detail sizes grouping based on Stock_abundances_at_szgroup.csv size bins. This is used to define the species distribution .shp files as well.</figcaption>
</figure>
</div>
</div>
<p>To calculate stock prices, we determine the average price per kilogram for each species based on revenue data from the VMS-TIX dataset, across the entire time series.</p>
<div class="cell" data-hash="populations_cache/html/fig-avg-prices_37e2773d9a72def6206eed41b9c506d4">
<div id="fig-avg-prices" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<table class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">species</th>
<th style="text-align: right;">rev_kg</th>
<th style="text-align: left;">fao_code</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">sablefish</td>
<td style="text-align: right;">6.938894</td>
<td style="text-align: left;">SAB</td>
</tr>
<tr class="even">
<td style="text-align: left;">sole dover</td>
<td style="text-align: right;">2.138809</td>
<td style="text-align: left;">MIP</td>
</tr>
<tr class="odd">
<td style="text-align: left;">thornyhead longspine</td>
<td style="text-align: right;">2.933431</td>
<td style="text-align: left;">SJZ</td>
</tr>
<tr class="even">
<td style="text-align: left;">thornyhead shortspine</td>
<td style="text-align: right;">6.594746</td>
<td style="text-align: left;">SJU</td>
</tr>
</tbody>
</table>
<figcaption class="figure-caption">Figure&nbsp;1.5: Average $/kg from fish ticket data.</figcaption>
</figure>
</div>
</div>
<p>Since we do not have information on price based on individual fish size, we can not categorize prices by size group. Thus we will assign the same average price to all categories and store it into the <code>Stock_prices_data.csv</code>.</p>
<div class="cell" data-hash="populations_cache/html/fig-stock-prices-data_cecefe1a0e7426088b98791a6fa21ba6">
<div id="fig-stock-prices-data" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<table class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">stock</th>
<th style="text-align: right;">small</th>
<th style="text-align: right;">medium</th>
<th style="text-align: right;">large</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">SAB</td>
<td style="text-align: right;">6.938894</td>
<td style="text-align: right;">6.938894</td>
<td style="text-align: right;">6.938894</td>
</tr>
<tr class="even">
<td style="text-align: left;">MIP</td>
<td style="text-align: right;">2.138809</td>
<td style="text-align: right;">2.138809</td>
<td style="text-align: right;">2.138809</td>
</tr>
<tr class="odd">
<td style="text-align: left;">SJZ</td>
<td style="text-align: right;">2.933431</td>
<td style="text-align: right;">2.933431</td>
<td style="text-align: right;">2.933431</td>
</tr>
<tr class="even">
<td style="text-align: left;">SJU</td>
<td style="text-align: right;">6.594746</td>
<td style="text-align: right;">6.594746</td>
<td style="text-align: right;">6.594746</td>
</tr>
</tbody>
</table>
<figcaption class="figure-caption">Figure&nbsp;1.6: Stock_prices_data.csv input file contects.</figcaption>
</figure>
</div>
</div>
</section>
<section id="files-overlook" class="level2" data-number="1.6">
<h2 data-number="1.6" class="anchored" data-anchor-id="files-overlook"><span class="header-section-number">1.6</span> Files overlook</h2>
<p><code>Stock_biological_traits.csv</code>:</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<colgroup>
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 0%">
<col style="width: 2%">
<col style="width: 2%">
<col style="width: 2%">
<col style="width: 3%">
<col style="width: 2%">
<col style="width: 2%">
<col style="width: 2%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 2%">
<col style="width: 3%">
<col style="width: 3%">
<col style="width: 2%">
<col style="width: 3%">
<col style="width: 3%">
<col style="width: 2%">
<col style="width: 2%">
<col style="width: 2%">
<col style="width: 1%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 2%">
<col style="width: 1%">
<col style="width: 2%">
<col style="width: 3%">
<col style="width: 2%">
<col style="width: 2%">
<col style="width: 2%">
<col style="width: 2%">
<col style="width: 1%">
<col style="width: 0%">
<col style="width: 0%">
<col style="width: 2%">
<col style="width: 6%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">UseIt</th>
<th style="text-align: left;">stock</th>
<th style="text-align: left;">Winf</th>
<th style="text-align: left;">k</th>
<th style="text-align: right;">Linf</th>
<th style="text-align: right;">CV_Linf</th>
<th style="text-align: right;">K</th>
<th style="text-align: right;">t0</th>
<th style="text-align: right;">a</th>
<th style="text-align: right;">b</th>
<th style="text-align: right;">L50</th>
<th style="text-align: left;">alpha</th>
<th style="text-align: left;">beta</th>
<th style="text-align: left;">r_age</th>
<th style="text-align: right;">tac_tons</th>
<th style="text-align: left;">fbar_age_min</th>
<th style="text-align: left;">fbar_age_max</th>
<th style="text-align: right;">F_target</th>
<th style="text-align: right;">F_percent</th>
<th style="text-align: right;">TAC_percent</th>
<th style="text-align: left;">B_trigger</th>
<th style="text-align: right;">FMSYlower</th>
<th style="text-align: right;">FMSYupper</th>
<th style="text-align: right;">FMSY</th>
<th style="text-align: right;">fbar_assessment</th>
<th style="text-align: right;">ssb_assessment</th>
<th style="text-align: right;">mls_cat</th>
<th style="text-align: right;">mls</th>
<th style="text-align: right;">sz_bin_cm</th>
<th style="text-align: right;">unit_sizebin</th>
<th style="text-align: right;">CV_recru</th>
<th style="text-align: right;">mat</th>
<th style="text-align: right;">mat_cat</th>
<th style="text-align: left;">etha_m</th>
<th style="text-align: left;">kappa</th>
<th style="text-align: left;">q</th>
<th style="text-align: left;">n</th>
<th style="text-align: left;">fzeroest</th>
<th style="text-align: left;">species</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Yes</td>
<td style="text-align: left;">SAB</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">58.62105</td>
<td style="text-align: right;">0.090500</td>
<td style="text-align: right;">0.374000</td>
<td style="text-align: right;">-1.1883843</td>
<td style="text-align: right;">3.3e-06</td>
<td style="text-align: right;">3.27136</td>
<td style="text-align: right;">52.66064</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">8474.875</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">0.069</td>
<td style="text-align: right;">0.0546881</td>
<td style="text-align: right;">0.0546881</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">0.057</td>
<td style="text-align: right;">0.0820</td>
<td style="text-align: right;">0.069</td>
<td style="text-align: right;">0.0208000</td>
<td style="text-align: right;">86995</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2.4696816</td>
<td style="text-align: right;">52.66064</td>
<td style="text-align: right;">9</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">Anoplopoma fimbria</td>
</tr>
<tr class="even">
<td style="text-align: left;">Yes</td>
<td style="text-align: left;">MIP</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">45.06160</td>
<td style="text-align: right;">0.080000</td>
<td style="text-align: right;">0.111500</td>
<td style="text-align: right;">-1.6668960</td>
<td style="text-align: right;">2.8e-06</td>
<td style="text-align: right;">3.35000</td>
<td style="text-align: right;">30.76170</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">50000.000</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">0.130</td>
<td style="text-align: right;">0.0000000</td>
<td style="text-align: right;">0.0000000</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">0.120</td>
<td style="text-align: right;">0.1300</td>
<td style="text-align: right;">0.130</td>
<td style="text-align: right;">0.0150000</td>
<td style="text-align: right;">221913</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.3609974</td>
<td style="text-align: right;">30.76170</td>
<td style="text-align: right;">5</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">Microstomus pacificus</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Yes</td>
<td style="text-align: left;">SJZ</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">28.18212</td>
<td style="text-align: right;">0.040000</td>
<td style="text-align: right;">0.108505</td>
<td style="text-align: right;">-0.3426386</td>
<td style="text-align: right;">4.3e-06</td>
<td style="text-align: right;">3.35200</td>
<td style="text-align: right;">17.82600</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">3331.750</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">0.071</td>
<td style="text-align: right;">-0.0398461</td>
<td style="text-align: right;">-0.0398461</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">0.068</td>
<td style="text-align: right;">0.0745</td>
<td style="text-align: right;">0.071</td>
<td style="text-align: right;">0.0236364</td>
<td style="text-align: right;">26771</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.6582776</td>
<td style="text-align: right;">17.82600</td>
<td style="text-align: right;">3</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">Sebastolobus altivelis</td>
</tr>
<tr class="even">
<td style="text-align: left;">Yes</td>
<td style="text-align: left;">SJU</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">95.20000</td>
<td style="text-align: right;">0.109034</td>
<td style="text-align: right;">0.013342</td>
<td style="text-align: right;">-7.1225000</td>
<td style="text-align: right;">4.8e-06</td>
<td style="text-align: right;">3.25500</td>
<td style="text-align: right;">31.40000</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">2345.250</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">0.017</td>
<td style="text-align: right;">-0.0346059</td>
<td style="text-align: right;">-0.0346059</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">0.016</td>
<td style="text-align: right;">0.0170</td>
<td style="text-align: right;">0.017</td>
<td style="text-align: right;">0.0091300</td>
<td style="text-align: right;">10135</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.5329404</td>
<td style="text-align: right;">31.40000</td>
<td style="text-align: right;">5</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">Sebastolobus alascanus</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><code>Stock_abundances_at_szgroup.csv</code>:</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<colgroup>
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 7%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">stock</th>
<th style="text-align: right;">0</th>
<th style="text-align: right;">1</th>
<th style="text-align: right;">2</th>
<th style="text-align: right;">3</th>
<th style="text-align: right;">4</th>
<th style="text-align: right;">5</th>
<th style="text-align: right;">6</th>
<th style="text-align: right;">7</th>
<th style="text-align: right;">8</th>
<th style="text-align: right;">9</th>
<th style="text-align: right;">10</th>
<th style="text-align: right;">11</th>
<th style="text-align: right;">12</th>
<th style="text-align: right;">13</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">SAB</td>
<td style="text-align: right;">16321</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">117071.1</td>
<td style="text-align: right;">900204.7</td>
<td style="text-align: right;">2957731.7</td>
<td style="text-align: right;">64443823</td>
<td style="text-align: right;">161069586</td>
<td style="text-align: right;">40030449</td>
<td style="text-align: right;">20453968.1</td>
<td style="text-align: right;">3586942.8</td>
<td style="text-align: right;">168015.2</td>
<td style="text-align: right;">35788.41</td>
<td style="text-align: right;">1226.409</td>
</tr>
<tr class="even">
<td style="text-align: left;">MIP</td>
<td style="text-align: right;">256930</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">46063450</td>
<td style="text-align: right;">125580385.4</td>
<td style="text-align: right;">67514127.9</td>
<td style="text-align: right;">148861830.9</td>
<td style="text-align: right;">342919698</td>
<td style="text-align: right;">170174509</td>
<td style="text-align: right;">33443062</td>
<td style="text-align: right;">925009.7</td>
<td style="text-align: right;">0.0</td>
<td style="text-align: right;">0.0</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">SJZ</td>
<td style="text-align: right;">68454</td>
<td style="text-align: right;">340982410</td>
<td style="text-align: right;">378117403</td>
<td style="text-align: right;">326556783.7</td>
<td style="text-align: right;">68729771.9</td>
<td style="text-align: right;">259346.3</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0.0</td>
<td style="text-align: right;">0.0</td>
<td style="text-align: right;">0.0</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.000</td>
</tr>
<tr class="even">
<td style="text-align: left;">SJU</td>
<td style="text-align: right;">13805</td>
<td style="text-align: right;">59005701</td>
<td style="text-align: right;">89485777</td>
<td style="text-align: right;">151768972.3</td>
<td style="text-align: right;">143613451.5</td>
<td style="text-align: right;">63939390.8</td>
<td style="text-align: right;">15344761</td>
<td style="text-align: right;">5834082</td>
<td style="text-align: right;">2397778</td>
<td style="text-align: right;">1447801.7</td>
<td style="text-align: right;">851419.2</td>
<td style="text-align: right;">210580.6</td>
<td style="text-align: right;">32859.72</td>
<td style="text-align: right;">0.000</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><code>Stock_abundance_at_age.csv</code>:</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: right;">year</th>
<th style="text-align: left;">stock</th>
<th style="text-align: right;">0</th>
<th style="text-align: right;">1</th>
<th style="text-align: right;">2</th>
<th style="text-align: right;">3</th>
<th style="text-align: right;">4</th>
<th style="text-align: right;">5</th>
<th style="text-align: right;">6</th>
<th style="text-align: right;">7</th>
<th style="text-align: right;">8</th>
<th style="text-align: right;">9</th>
<th style="text-align: right;">10</th>
<th style="text-align: right;">11</th>
<th style="text-align: right;">12</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">2022</td>
<td style="text-align: left;">SAB</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: right;">2022</td>
<td style="text-align: left;">MIP</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2022</td>
<td style="text-align: left;">SJZ</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: right;">2022</td>
<td style="text-align: left;">SJU</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><code>Stock_prices_data.csv</code>:</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">stock</th>
<th style="text-align: right;">small</th>
<th style="text-align: right;">medium</th>
<th style="text-align: right;">large</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">SAB</td>
<td style="text-align: right;">6.938894</td>
<td style="text-align: right;">6.938894</td>
<td style="text-align: right;">6.938894</td>
</tr>
<tr class="even">
<td style="text-align: left;">MIP</td>
<td style="text-align: right;">2.138809</td>
<td style="text-align: right;">2.138809</td>
<td style="text-align: right;">2.138809</td>
</tr>
<tr class="odd">
<td style="text-align: left;">SJZ</td>
<td style="text-align: right;">2.933431</td>
<td style="text-align: right;">2.933431</td>
<td style="text-align: right;">2.933431</td>
</tr>
<tr class="even">
<td style="text-align: left;">SJU</td>
<td style="text-align: right;">6.594746</td>
<td style="text-align: right;">6.594746</td>
<td style="text-align: right;">6.594746</td>
</tr>
</tbody>
</table>
</div>
</div>


<div id="refs" class="references csl-bib-body hanging-indent" role="list" style="display: none">
<div id="ref-adams2019longspine" class="csl-entry" role="listitem">
Adams, Grant D., Owen S. Hamel, and Ian G. Taylor. 2019. <span>“Catch Only Update: Stock Assessment and Status of Longspine Thornyhead (Sebastolobus Altivelis) Off California, Oregon and Washington in 2019.”</span> Seattle, Washington: School of Aquatic; Fishery Sciences, University of Washington; Northwest Fisheries Science Center, U.S. Department of Commerce, National Oceanic; Atmospheric Administration, National Marine Fisheries Service. <a href="https://www.pcouncil.org/documents/2019/09/agenda-item-h-5-supplemental-revised-attachment-23.pdf/">https://www.pcouncil.org/documents/2019/09/agenda-item-h-5-supplemental-revised-attachment-23.pdf/</a>.
</div>
<div id="ref-blanchard2017sizespectra" class="csl-entry" role="listitem">
Blanchard, Julia L, Ryan F Heneghan, Jason D Everett, Rowan Trebilco, and Anthony J Richardson. 2017. <span>“From Bacteria to Whales: Using Functional Size Spectra to Model Marine Ecosystems.”</span> <em>Trends in Ecology &amp; Evolution</em> 32 (3): 174–86. <a href="https://doi.org/10.1016/j.tree.2016.12.003">https://doi.org/10.1016/j.tree.2016.12.003</a>.
</div>
<div id="ref-fay2005longspine" class="csl-entry" role="listitem">
Fay, G. 2005. <span>“Stock Assessment and Status of Longspine Thornyhead (Sebastolobus Altivelis) Off California, Oregon and Washington in 2005.”</span> Portland, Or: PFMC. <a href="https://www.pcouncil.org/documents/2020/12/stock-assessment-and-status-of-longspine-thornyhead-sebastolobus-altivelis-off-california-oregon-and-washington-in-2005-august-30-2005.pdf/">https://www.pcouncil.org/documents/2020/12/stock-assessment-and-status-of-longspine-thornyhead-sebastolobus-altivelis-off-california-oregon-and-washington-in-2005-august-30-2005.pdf/</a>.
</div>
<div id="ref-guzman2017sablefish" class="csl-entry" role="listitem">
Guzmán, José M, J Adam Luckenbach, Mollie A Middleton, Kenneth C Massee, Cortney Jensen, Frederick W Goetz, Andrew J Jasonowicz, and Penny Swanson. 2017. <span>“Reproductive Life History of Sablefish (Anoplopoma Fimbria) from the US Washington Coast.”</span> <em>Plos One</em> 12 (9): e0184413. <a href="https://doi.org/10.1371/journal.pone.0184413">https://doi.org/10.1371/journal.pone.0184413</a>.
</div>
<div id="ref-haltuch2019sablefish" class="csl-entry" role="listitem">
Haltuch, MA, KF Johnson, N Tolimieri, MS Kapur, and CA Castillo-Jordán. 2019. <span>“Status of the Sablefish Stock in u.s. Waters in 2019.”</span> 7700 Ambassador Place NE, Suite 200, Portland, OR: Pacific Fisheries Management Council. <a href="https://www.pcouncil.org/documents/2019/10/status-of-the-sablefish-stock-in-u-s-waters-in-2019-october-22-2019.pdf/">https://www.pcouncil.org/documents/2019/10/status-of-the-sablefish-stock-in-u-s-waters-in-2019-october-22-2019.pdf/</a>.
</div>
<div id="ref-haltuch2019sablefish_benchmark" class="csl-entry" role="listitem">
Haltuch, Melissa A., Kelli F. Johnson, Nick Tolimieri, Maia S. Kapur, and Claudio A. Castillo-Jordán. 2019. <span>“Status of the Sablefish Stock in u.s. Waters in 2019.”</span> Seattle, WA, USA: National Marine Fisheries Service, Northwest Fisheries Science Center. <a href="https://www.pcouncil.org/documents/2019/10/status-of-the-sablefish-stock-in-u-s-waters-in-2019-october-22-2019.pdf/">https://www.pcouncil.org/documents/2019/10/status-of-the-sablefish-stock-in-u-s-waters-in-2019-october-22-2019.pdf/</a>.
</div>
<div id="ref-head2014maturity" class="csl-entry" role="listitem">
Head, MA, AA Keller, and M Bradburn. 2014. <span>“Maturity and Growth of Sablefish, Anoplopoma Fimbria, Along the US West Coast.”</span> <em>Fisheries Research</em> 159: 56–67. <a href="https://doi.org/10.1016/j.fishres.2014.05.007">https://doi.org/10.1016/j.fishres.2014.05.007</a>.
</div>
<div id="ref-head2014sablefish" class="csl-entry" role="listitem">
Head, Melissa A, Aimee A Keller, and Mark Bradburn. 2014. <span>“Maturity and Growth of Sablefish, Anoplopoma Fimbria, Along the US West Coast.”</span> <em>Fisheries Research</em> 159: 56–67. <a href="https://doi.org/10.1016/j.fishres.2014.05.007">https://doi.org/10.1016/j.fishres.2014.05.007</a>.
</div>
<div id="ref-hunter1990doversole" class="csl-entry" role="listitem">
Hunter, John R., John L. Butler, Carol Kimbrell, and Eric A. Lynn. 1990. <span>“Bathymetric Patterns in Size, Age, Sexual Maturity, Water Content, and Caloric Density of Dover Sole, *Microstomus Pacificus*.”</span> <em>CalCOFI Investigative Reports</em> 31: 132–44. <a href="https://calcofi.com/publications/calcofireports/v31/Vol_31_Hunter_etal.pdf">https://calcofi.com/publications/calcofireports/v31/Vol_31_Hunter_etal.pdf</a>.
</div>
<div id="ref-jacobson1993bathymetric" class="csl-entry" role="listitem">
Jacobson, LD, and JR Hunter. 1993. <span>“Bathymetric Demography and Management of Dover Sole.”</span> <em>North American Journal of Fisheries Management</em> 13 (3): 405–20.
</div>
<div id="ref-johnson2023sablefish" class="csl-entry" role="listitem">
Johnson, Kelli F., Chantel R. Wetzel, and Nick Tolimieri. 2023. <span>“Status of Sablefish (Anoplopoma Fimbria) Along the u.s. West Coast in 2023.”</span> 2725 Montlake Boulevard East, Seattle, Washington 98112: Northwest Fisheries Science Center, U.S. Department of Commerce, National Oceanic; Atmospheric Administration, National Marine Fisheries Service. <a href="https://www.pcouncil.org/documents/2024/02/status-of-sablefish-anoplopoma-fimbria-along-the-u-s-west-coast-in-2023.pdf/">https://www.pcouncil.org/documents/2024/02/status-of-sablefish-anoplopoma-fimbria-along-the-u-s-west-coast-in-2023.pdf/</a>.
</div>
<div id="ref-liu2023species" class="csl-entry" role="listitem">
Liu, Owen R, Eric J Ward, Sean C Anderson, Kelly S Andrews, Lewis AK Barnett, Stephanie Brodie, Gemma Carroll, et al. 2023. <span>“Species Redistribution Creates Unequal Outcomes for Multispecies Fisheries Under Projected Climate Change.”</span> <em>Science Advances</em> 9 (33): eadg5468. <a href="https://www.science.org/doi/full/10.1126/sciadv.adg5468">https://www.science.org/doi/full/10.1126/sciadv.adg5468</a>.
</div>
<div id="ref-PFMC2016" class="csl-entry" role="listitem">
Pacific Fishery Management Council. 2016. <span>“2017-2018 Groundfish Harvest Specifications and Management Measures Including Changes to Groundfish Stock Designations (Amendment 27 to the Pacific Coast Groundfish Fishery Management Plan): Description and Analysis for Council Decision-Making.”</span> Report. Suite 101, 7700 NE Ambassador Place, Portland, OR 97220: Pacific Fishery Management Council. <a href="https://www.pcouncil.org/documents/2016/09/2017-2018-groundfish-harvest-specifications-and-management-measures-analytical-document-revised.pdf/">https://www.pcouncil.org/documents/2016/09/2017-2018-groundfish-harvest-specifications-and-management-measures-analytical-document-revised.pdf/</a>.
</div>
<div id="ref-PFMC2018" class="csl-entry" role="listitem">
———. 2018. <span>“Pacific Coast Groundfish Fishery 2019–20 Harvest Specifications, Yelloweye Rebuilding Plan Revisions, and Management Measures.”</span> Report. 7600 Sand Point Way NE, Seattle, WA 98115: Pacific Fishery Management Council. <a href="https://www.pcouncil.org/documents/2020/12/final-environmental-assessment-magnuson-stevens-act-analysis-regulatory-impact-review-regulatory-flexibility-act-analysis-pacific-coast-groundfish-fishery-2019-20-harvest-specifications-yelloweye-re.pdf/">https://www.pcouncil.org/documents/2020/12/final-environmental-assessment-magnuson-stevens-act-analysis-regulatory-impact-review-regulatory-flexibility-act-analysis-pacific-coast-groundfish-fishery-2019-20-harvest-specifications-yelloweye-re.pdf/</a>.
</div>
<div id="ref-PFMC2020" class="csl-entry" role="listitem">
———. 2020. <span>“Preferred 2021 and 2022 Harvest Specifications, Acceptable Biological Catches, and Annual Catch Limits for West Coast Groundfish Stocks and Stock Complexes Under Preferred Harvest Specifications.”</span> Report. Suite 101, 7700 NE Ambassador Place, Portland, OR 97220: Pacific Fishery Management Council. <a href="https://www.pcouncil.org/documents/2020/05/f-1-attachment-7-preferred-2021-and-2022-harvest-specifications-acceptable-biological-catches-and-annual-catch-limits-for-west-coast-groundfish-stocks-and-stock-complexes-under-preferred-harvest-c.pdf/">https://www.pcouncil.org/documents/2020/05/f-1-attachment-7-preferred-2021-and-2022-harvest-specifications-acceptable-biological-catches-and-annual-catch-limits-for-west-coast-groundfish-stocks-and-stock-complexes-under-preferred-harvest-c.pdf/</a>.
</div>
<div id="ref-PFMC2022" class="csl-entry" role="listitem">
———. 2022. <span>“Pacific Coast Groundfish Fishery 2023-2024 Harvest Specifications and Management Measures: Draft Analytical Document, the Preferred Alternative.”</span> Report. Suite 101, 7700 NE Ambassador Place, Portland, OR 97220: Pacific Fishery Management Council. <a href="https://www.pcouncil.org/documents/2022/08/draft-management-measure-analytical-document-the-preferred-alternative-september-2022.pdf/">https://www.pcouncil.org/documents/2022/08/draft-management-measure-analytical-document-the-preferred-alternative-september-2022.pdf/</a>.
</div>
<div id="ref-pearson2003reproductive" class="csl-entry" role="listitem">
Pearson, KE, and DR Gunderson. 2003. <span>“Reproductive Biology and Ecology of Shortspine Thornyhead Rockfish, Sebastolobus Alascanus, and Longspine Thornyhead Rockfish, s. Altivelis, from the Northeastern Pacific Ocean.”</span> <em>Environmental Biology of Fishes</em> 67: 117–36.
</div>
<div id="ref-rodgveller2016sablefish" class="csl-entry" role="listitem">
Rodgveller, Cara J., James W. Stark, and Katy B. Echave. 2016. <span>“Age at Maturity, Skipped Spawning, and Fecundity of Female Sablefish (Anoplopoma Fimbria) During the Spawning Season.”</span> <em>Fishery Bulletin</em> 114 (1): 89–102. <a href="https://repository.library.noaa.gov/view/noaa/12546">https://repository.library.noaa.gov/view/noaa/12546</a>.
</div>
<div id="ref-stephens2014longspine" class="csl-entry" role="listitem">
Stephens, A, and IG Taylor. 2013. <span>“Stock Assessment and Status of Longspine Thornyhead (Sebastolobus Altivelis) Off California, Oregon and Washington in 2013.”</span> Portland, Or: PFMC. <a href="https://www.pcouncil.org/documents/2014/02/stock-assessment-and-status-of-longspine-thornyhead-sebastolobus-altivelis-off-california-oregon-and-washington-in-2013-published-january-5-2014.pdf/">https://www.pcouncil.org/documents/2014/02/stock-assessment-and-status-of-longspine-thornyhead-sebastolobus-altivelis-off-california-oregon-and-washington-in-2013-published-january-5-2014.pdf/</a>.
</div>
<div id="ref-stockhausen2005doversole" class="csl-entry" role="listitem">
Stockhausen, William T., Benjamin J. Turnock, Z. Teresa A’mar, Mark E. Wilkins, and Michael H. Martin. 2005. <span>“4a. Gulf of Alaska Dover Sole.”</span> <a href="https://apps-afsc.fisheries.noaa.gov/refm/docs/2005/GOAdover.pdf">https://apps-afsc.fisheries.noaa.gov/refm/docs/2005/GOAdover.pdf</a>.
</div>
<div id="ref-wetzel2021doversole_benchmark" class="csl-entry" role="listitem">
Wetzel, Chantel R., and Aaron M. Berger. 2021. <span>“Status of Dover Sole (Microstomus Pacificus) Along the u.s. West Coast in 2021.”</span> Seattle, Washington; Newport, Oregon: Northwest Fisheries Science Center, U.S. Department of Commerce, National Oceanic; Atmospheric Administration, National Marine Fisheries Service. <a href="https://www.pcouncil.org/documents/2021/10/status-of-dover-sole-microstomus-pacificus-along-the-u-s-west-coast-in-2021.pdf/">https://www.pcouncil.org/documents/2021/10/status-of-dover-sole-microstomus-pacificus-along-the-u-s-west-coast-in-2021.pdf/</a>.
</div>
<div id="ref-zahner2023status" class="csl-entry" role="listitem">
Zahner, JA, MA Heller-Shipley, HA Oleynik, SG Beyer, P-Y Hernvann, M Véron, AN Odell, et al. 2023. <span>“Status of Shortspine Thornyhead (Sebastolobus Alascanus) Along the US West Coast in 2023.”</span> Portland, Oregon: Pacific Fishery Management Council.
</div>
<div id="ref-zahner2023shortspine" class="csl-entry" role="listitem">
Zahner, Joshua A., Madison Heller-Shipley, Haley A. Oleynik, Sabrina G. Beyer, Pierre-Yves Hernvann, Matthieu Véron, Andrea N. Odell, et al. 2023. <span>“Status of Shortspine Thornyhead (Sebastolobus Alascanus) Along the US West Coast in 2023.”</span> Seattle, Washington; Vancouver, British Columbia; Santa Cruz, California; Davis, California; Juneau, Alaska: School of Aquatic; Fishery Sciences, University of Washington; Institute for the Oceans; Fisheries, University of British Columbia; Institute of Marine Sciences’ Fisheries Collaborative Program, University of California-Santa Cruz; Northwest Fisheries Science Center, U.S. Department of Commerce, National Oceanic; Atmospheric Administration, National Marine Fisheries Service; Alaska Fisheries Science Center, U.S. Department of Commerce, National Oceanic; Atmospheric Administration, National Marine Fisheries Service; University of California Davis. <a href="https://www.pcouncil.org/documents/2024/02/status-of-shortspine-thornyhead-sebastolobus-alascanus-along-the-us-west-coast-in-2023.pdf/">https://www.pcouncil.org/documents/2024/02/status-of-shortspine-thornyhead-sebastolobus-alascanus-along-the-us-west-coast-in-2023.pdf/</a>.
</div>
</div>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./index.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Introduction</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./fisheries.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Fisheries data</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>